// Generated by `pnpm bindings` from crates/core/src/types.rs. Do not edit.
/* eslint-disable */
// This file has been generated by Specta. Do not edit this file manually.
export type BackupInfo = {
	name: string,
	at: number,
	workspaces: number,
};

/**  `labels` are data (server names, repo names, file names), never English sentences. */
export type BusyItem = {
	kind: BusyKind,
	count: number,
	labels: string[],
};

export type BusyKind = "gitRun" | "gitOp" | "agent" | "devServer" | "check" | "terminal" | "preview" | "mongo" | "unsaved";

export type BusyReport = {
	blocking: BusyItem[],
	confirmable: BusyItem[],
};

export type Change = {
	path: string,
	origPath?: string | null,
	kind: ChangeKind,
	/**  One character, `" "` if none. */
	indexStatus: string,
	/**  One character, `" "` if none. */
	worktreeStatus: string,
	staged: boolean,
	partiallyStaged: boolean,
	guard: GuardState,
	binary?: boolean | null,
	sizeBytes?: number,
	/**  Collapsed untracked directory; `path` ends with `/`. */
	dir?: boolean | null,
};

export type ChangeKind = "modified" | "added" | "deleted" | "renamed" | "copied" | "typeChanged" | "untracked" | "conflicted" | "submodule";

export type ChangedFile = {
	path: string,
	origPath?: string | null,
	kind: ChangeKind,
};

export type CommitInfo = {
	oid: string,
	shortOid: string,
	subject: string,
	author: string,
	dateMs: number,
};

export type CommitRequest = {
	/**  uuid from the caller */
	runId: string,
	repos: RepoCommit[],
	noVerify: boolean,
};

/**  The workspace the last two launches never finished opening (crash-loop guard): the app starts on Welcome. */
export type CrashLoopNotice = {
	id: string,
	name: string,
};

export type CreateResult = {
	entry: WorkspaceEntry,
	reused: boolean,
};

export type DiffSource = { kind: "worktreeVsHead" } | { kind: "stagedVsHead" } | { kind: "commit"; oid: string };

export type DoctorRepo = {
	repoId: string,
	lsRemoteOk: boolean,
	hooks: HookInfo,
	message?: string | null,
};

export type DoctorReport = {
	gitPath: string,
	gitVersion: string,
	credentialHelpers: string[],
	pathHasNode: boolean,
	repos: DoctorRepo[],
};

/**  The only error type of the engine facade; serialised as-is to the UI. */
export type EngineError = {
	code: string,
	message: string,
	detail?: string | null,
};

export type EngineStatus = {
	env: EnvStatus,
	repoIds: string[],
};

export type EnvSource = "login-shell" | "fallback";

export type EnvState = "resolving" | "ready" | "failed";

export type EnvStatus = {
	state: EnvState,
	gitPath: string,
	nodePath?: string | null,
	source: EnvSource,
	message?: string | null,
};

export type Failure = {
	kind: FailureKind,
	message: string,
	output?: string | null,
};

export type FailureKind = "hookRejected" | "nothingToCommit" | "emptyMessage" | "conflict" | "lockBusy" | "headMoved" | "auth" | "nonFastForward" | "remoteDeclined" | "network" | "guardBlocked" | "invalidSelection" | "unknown";

export type FileContents = {
	path: string,
	original: string,
	modified: string,
	binary: boolean,
	tooLarge: boolean,
	guard: GuardState,
	language?: string | null,
};

export type FileSelection = { mode: "whole"; path: string; origPath?: string | null } | { mode: "partial"; path: string; hunks: HunkSelection[] };

export type ForceWithLease = {
	seenOid: string,
};

export type GuardState = "ok" | "neverAdd" | "secret" | "tooLarge" | "sensitive";

export type HeadInfo = {
	branch?: string | null,
	oid?: string | null,
	detached: boolean,
	unborn: boolean,
};

export type HookInfo = {
	kind: HookKind,
	path?: string | null,
};

export type HookKind = "none" | "husky" | "custom";

export type Hunk = {
	index: number,
	header: string,
	oldStart: number,
	oldLines: number,
	newStart: number,
	newLines: number,
	lines: HunkLine[],
};

export type HunkLine = {
	kind: HunkLineKind,
	text: string,
};

export type HunkLineKind = "context" | "add" | "del";

export type HunkSelection = {
	index: number,
	/**  Indexes into `Hunk::lines`; `None` selects the whole hunk. */
	lines?: number[] | null,
};

export type MessageMode = "shared" | "perRepo";

export type OpEvent = {
	runId: string,
	repoId: string,
	kind: OpKind,
	status: StepStatus,
	line?: OpLine | null,
	percent?: number | null,
};

export type OpKind = "commit" | "push" | "pull" | "fetch";

export type OpLine = {
	stream: StreamKind,
	text: string,
};

export type OpResult = {
	runId: string,
	kind: OpKind,
	repos: RepoOutcome[],
	finishedAtMs: number,
};

/**  Why the active workspace could not be opened at launch. */
export type OpenError = {
	id: string,
	reason: OpenErrorReason,
};

export type OpenErrorReason = "allMissing" | "fileDamaged" | "fileMissing";

export type OutgoingInfo = {
	repoId: string,
	local: string,
	remote: string,
	remoteBranch: string,
	newRemoteBranch: boolean,
	protected: boolean,
	commits: CommitInfo[],
	staleAsOfMs?: number,
	checkedByDefault: boolean,
	canPush: boolean,
	blockedReason?: string | null,
	/**
	 *  Commits on the remote-tracking branch that the local branch lacks (a forced push would drop them);
	 *  absent while the tracking ref does not exist.
	 */
	remoteOnly?: number | null,
	/**
	 *  Tip of the remote-tracking branch this plan was computed against (the lease value of a forced push);
	 *  absent while the tracking ref does not exist.
	 */
	remoteOid?: string | null,
};

export type ProblemKind = "corrupt" | "newerVersion" | "legacyUnreadable" | "ioError" | "testJail" | "otherInstance";

/**  Branch patterns that apply to one repository, whatever workspace it is opened from (I7). */
export type Protection = {
	protected: string[],
	live: string[],
};

export type PullMode = "ffOnly" | "merge" | "rebase";

export type PushFlag = " " | "+" | "-" | "*" | "=" | "!";

export type PushRefResult = {
	flag: PushFlag,
	from: string,
	to: string,
	summary: string,
	reason?: string | null,
};

export type PushRequest = {
	runId: string,
	targets: PushTarget[],
	noVerify: boolean,
};

export type PushTarget = {
	repoId: string,
	remote: string,
	remoteBranch: string,
	tags: TagsMode,
	forceWithLease?: ForceWithLease | null,
	/**  The remote branch name typed by the human; required when the target is a live branch. */
	confirmLive?: string | null,
};

export type PushTargetMapping = {
	remote: string,
	branch: string,
};

export type RegistryProblem = {
	kind: ProblemKind,
	message: string,
	backups: BackupInfo[],
};

export type RegistryView = {
	version: number,
	rev: number,
	activeId: string | null,
	pinned: boolean,
	workspaces: WorkspaceSummary[],
	problem: RegistryProblem | null,
	openError: OpenError | null,
	/**  Epoch of the running engine generation (filled by the app, not by the registry). */
	epoch?: number | null,
	crashLoop?: CrashLoopNotice | null,
	/**  This launch migrated the legacy `workspace.json`: the page shows its one-time notice (filled by the app, once). */
	justMigrated?: boolean,
	/**  `INTELY_WORKSPACES` was set but ignored because no jail is active. */
	envIgnored?: boolean,
};

export type RepoCommit = {
	repoId: string,
	files: FileSelection[],
	message: string,
	amend: boolean,
};

export type RepoConfig = {
	id: string,
	path: string,
	name: string,
	/**  `#rrggbb` */
	color: string,
	/**  1-2 characters */
	badge: string,
	order: number,
	/**  Local branch -> push target; never written to git config. */
	pushTargets: { [key in string]: PushTargetMapping },
};

export type RepoOutcome = {
	repoId: string,
	status: StepStatus,
	commitOid?: string | null,
	/**  Commit succeeded but the real-index reset is still pending. */
	reconciled: boolean,
	failure?: Failure | null,
	hookModifiedFiles: string[],
	pushResults?: PushRefResult[] | null,
};

export type RepoProbe = {
	repoId: string,
	status: RepoStatus,
	branch: string | null,
	detached: boolean,
};

export type RepoSnapshot = {
	repoId: string,
	/**  Monotonic per repo. */
	revision: number,
	takenAtMs: number,
	head: HeadInfo,
	upstream?: UpstreamInfo | null,
	ahead: number,
	behind: number,
	state: RepoState,
	hooks: HookInfo,
	changes: Change[],
	stashCount: number,
	worktreeCount: number,
	error?: string | null,
};

export type RepoState = "normal" | "merging" | "rebasing" | "cherryPicking" | "reverting" | "bisecting";

export type RepoStatus = "ok" | "missing" | "volumeMissing" | "notRepo" | "noAccess" | "unresponsive";

export type RepoSummary = {
	id: string,
	name: string,
	color: string,
	badge: string,
	path: string,
};

export type RunStarted = {
	runId: string,
};

export type StepStatus = "queued" | "preparing" | "hooks" | "committing" | "reconciling" | "pushing" | "done" | "skipped" | "failed" | "cancelled";

export type StreamKind = "stdout" | "stderr";

/**  A process of the old workspace that ignored the group kill. */
export type Survivor = {
	pid: number,
	port: number | null,
	cwd: string,
	kind: SurvivorKind,
};

export type SurvivorKind = "devServer" | "terminal" | "check" | "preview";

export type SwitchResult = {
	activeId: string | null,
	epoch: number,
	warnings: SwitchWarning[],
	survivors: Survivor[],
};

/**  A subsystem that did not finish in its budget; `code` is e.g. `runnerStuck`, translated by the UI. */
export type SwitchWarning = {
	code: string,
	subsystem: string,
};

export type TagsMode = "none" | "follow" | "all";

export type UntrackedList = {
	files: Change[],
	truncated: boolean,
};

export type UpstreamInfo = {
	remote: string,
	branch: string,
	gone: boolean,
};

export type Workspace = {
	version: number,
	repos: RepoConfig[],
	protectedBranches: string[],
	/**  Extra live-branch patterns per repo id, merged with `protectedBranches` (default empty). */
	liveBranches?: { [key in string]: string[] },
	settings: WorkspaceSettings,
};

/**  One line of `workspaces.json`. */
export type WorkspaceEntry = {
	id: string,
	name: string,
	/**  `#rrggbb` */
	color: string,
	order: number,
	createdAt: number,
	lastOpenedAt: number | null,
	origin: WorkspaceOrigin,
};

/**  State of a workspace's own file as the registry sees it. */
export type WorkspaceFileState = "ok" | "damaged" | "missing";

export type WorkspaceOrigin = "created" | "duplicate" | "openedFolder" | "scanned" | "migrated";

export type WorkspaceProbe = {
	id: string,
	repos: RepoProbe[],
};

export type WorkspaceSettings = {
	messageMode: MessageMode,
	untrackedChecked: boolean,
};

export type WorkspaceSummary = {
	id: string,
	name: string,
	color: string,
	order: number,
	createdAt: number,
	lastOpenedAt: number | null,
	origin: WorkspaceOrigin,
	repos: RepoSummary[],
	/**  Absent when everything is fine (older UIs ignore it). */
	fileState?: WorkspaceFileState | null,
};
