//! TypeScript export (providers-plan 5.3): one specta run, split into
//! `packages/protocol/src/generated/{events,policy,providers,usage,sidecar,enforcement,api}.ts`, plus the
//! Rust-produced fixtures the TypeScript tests parse (`packages/protocol/fixtures/*.json`).

use std::collections::{BTreeMap, BTreeSet};
use std::io;
use std::path::Path;

use serde_json::{json, Value};
use specta::Types;
use specta_typescript::Typescript;

use crate::api::*;
use crate::events::samples::{cases, intent_cases, sample_events};
use crate::events::types::*;
use crate::events::{Violation, ViolationCode};
use crate::mcp::{McpExposure, McpPolicy};
use crate::policy::decide::{Decision, PolicyDecision, SessionAllowKind, SessionAllowOffer};
use crate::policy::enforcement::*;
use crate::policy::intent::*;
use crate::providers::*;
use crate::sidecar::*;
use crate::usage::*;

/// Which generated file each exported type lands in. Every type must appear exactly once.
const FILES: &[(&str, &[&str])] = &[
    (
        "events",
        &[
            "AgentEvent", "AttachmentRef", "BatchEvent", "EventKind", "Effective", "EffectiveChange", "AuthFact", "ToolDiff", "PermissionOption", "QuestionOption", "PlanItem",
            "ToolKind", "ToolStatus", "DecidedBy", "PermissionOutcome", "ModeChangeReason", "StatusState", "ErrorClass", "StopReason", "Violation", "ViolationCode", "McpServerState", "McpServerInfo", "McpToolInfo", "McpServerStatus",
        ],
    ),
    ("api", &["RunStatus", "PermissionDecision", "Requested", "AgentEffective", "AgentSummary", "AutoQueue", "AutoInfo", "RoleInfo", "AgentStartRequest", "AgentAttachment", "QuestionAnswer"]),
    ("policy", &["ToolClass", "ToolIntent", "Actor", "SubagentFlags", "PolicyRequest", "Decision", "PolicyDecision", "SessionAllowKind", "SessionAllowOffer"]),
    ("mcp", &["McpPolicy", "McpExposure"]),
    ("delegates", &["DelegateScope", "ExcludeReason", "DelegateSpec", "DelegateInfo", "ExcludedDelegate"]),
    (
        "providers",
        &[
            "AttachmentsCap", "Cap", "CapKey", "CapEntry", "ProviderCaps", "ModelPrice", "ModelInfo", "SettingField", "SettingKind", "DetectSpec", "ProviderDef", "Detection",
            "ProviderKind", "ProviderHost", "AuthMode", "ProviderState", "AuthState", "Effort", "PermissionMode",
        ],
    ),
    ("usage", &["CostBasis", "TokenCounts", "ModelTokens", "UsageRecord"]),
    (
        "sidecar",
        &[
            "SidecarMsg", "SidecarBody", "SessionStart", "SessionEnv", "ResumeRef", "AcpLaunch", "SettingSource", "ResolvedRole", "AuthHandoff", "SlotAcquire", "LeaseGrant",
            "ReplyError", "SessionStarted", "Acknowledged", "Reply", "Secret", "McpStatusReply", "McpToggle",
        ],
    ),
    ("enforcement", &["Tier", "Suite", "SuiteResult", "Layer", "EnforcementKey", "EnforcementRun", "EnforcementChip"]),
];

const HEADER: &str = "// Generated by `pnpm protocol:gen` from crates/agent_core. Do not edit.\n/* eslint-disable */\n";

pub fn type_collection() -> Types {
    Types::default()
        .register::<AgentEvent>()
        .register::<EventKind>()
        .register::<Violation>()
        .register::<ViolationCode>()
        .register::<PolicyRequest>()
        .register::<PolicyDecision>()
        .register::<Decision>()
        .register::<ProviderCaps>()
        .register::<ModelInfo>()
        .register::<ProviderDef>()
        .register::<Detection>()
        .register::<ProviderState>()
        .register::<UsageRecord>()
        .register::<SidecarMsg>()
        .register::<EnforcementRun>()
        .register::<EnforcementChip>()
        .register::<AgentSummary>()
        .register::<RoleInfo>()
        .register::<AgentStartRequest>()
        .register::<AgentAttachment>()
        .register::<QuestionAnswer>()
        .register::<PermissionDecision>()
        .register::<RunStatus>()
        .register::<AutoInfo>()
        .register::<SessionAllowKind>()
        .register::<SessionAllowOffer>()
        .register::<McpPolicy>()
        .register::<McpExposure>()
}

/// `(name, block)` for every top-level `export type`, with its doc comment.
fn blocks(flat: &str) -> Vec<(String, String)> {
    flat.split("\n\n")
        .map(str::trim)
        .filter(|b| b.contains("export type "))
        .map(|b| {
            let after = b.split("export type ").nth(1).unwrap_or_default();
            let name: String = after.chars().take_while(|c| c.is_alphanumeric() || *c == '_').collect();
            (name, b.to_string())
        })
        .collect()
}

/// Identifiers that look like type names, outside comments.
fn referenced(block: &str) -> BTreeSet<String> {
    let code: String = {
        let mut out = String::new();
        let mut rest = block;
        while let Some(i) = rest.find("/**") {
            out.push_str(&rest[..i]);
            rest = rest[i..].find("*/").map_or("", |j| &rest[i + j + 2..]);
        }
        out.push_str(rest);
        out
    };
    let mut names = BTreeSet::new();
    let mut word = String::new();
    let mut in_string = false;
    for c in code.chars().chain(std::iter::once(' ')) {
        if c == '"' {
            in_string = !in_string;
        }
        if !in_string && (c.is_alphanumeric() || c == '_') {
            word.push(c);
        } else {
            if word.chars().next().is_some_and(|f| f.is_ascii_uppercase()) {
                names.insert(std::mem::take(&mut word));
            }
            word.clear();
        }
    }
    names
}

/// `generated/<file>.ts` contents by file stem.
pub fn typescript_files() -> BTreeMap<String, String> {
    let flat = Typescript::default().header("").export(&type_collection(), specta_serde::Format).expect("export TypeScript");
    let all = blocks(&flat);
    let file_of: BTreeMap<&str, &str> = FILES.iter().flat_map(|(f, names)| names.iter().map(move |n| (*n, *f))).collect();
    for (name, _) in &all {
        assert!(file_of.contains_key(name.as_str()), "exported type {name} has no file in export.rs FILES");
    }
    let have: BTreeSet<&str> = all.iter().map(|(n, _)| n.as_str()).collect();
    for name in file_of.keys() {
        assert!(have.contains(name), "FILES lists {name}, which is not exported");
    }
    let mut out = BTreeMap::new();
    for (file, _) in FILES {
        let mut own: Vec<&(String, String)> = all.iter().filter(|(n, _)| file_of[n.as_str()] == *file).collect();
        own.sort_by(|a, b| a.0.cmp(&b.0));
        let mut imports: BTreeMap<&str, BTreeSet<String>> = BTreeMap::new();
        for (name, block) in &own {
            for r in referenced(block) {
                if r != *name {
                    if let Some(from) = file_of.get(r.as_str()).filter(|f| **f != *file) {
                        imports.entry(from).or_default().insert(r);
                    }
                }
            }
        }
        let mut text = String::from(HEADER);
        for (from, names) in &imports {
            text.push_str(&format!("import type {{ {} }} from \"./{from}\";\n", names.iter().cloned().collect::<Vec<_>>().join(", ")));
        }
        text.push('\n');
        text.push_str(&own.iter().map(|(_, b)| b.as_str()).collect::<Vec<_>>().join("\n\n"));
        text.push('\n');
        out.insert(file.to_string(), text);
    }
    out
}

fn pretty(v: &Value) -> String {
    let mut s = serde_json::to_string_pretty(v).unwrap_or_default();
    s.push('\n');
    s
}

/// `fixtures/<name>.json` contents, all produced by Rust.
pub fn fixture_files() -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    out.insert("events.json".to_string(), pretty(&serde_json::to_value(sample_events()).unwrap_or_default()));
    let invariant_cases: Vec<Value> = cases()
        .into_iter()
        .map(|c| json!({"name": c.name, "events": c.events, "expect": c.expect}))
        .collect();
    out.insert("invariant-cases.json".to_string(), pretty(&Value::Array(invariant_cases)));
    let intents: Vec<Value> = intent_cases().into_iter().map(|(tool, input, intent)| json!({"tool": tool, "input": input, "intent": intent})).collect();
    out.insert("intent-cases.json".to_string(), pretty(&Value::Array(intents)));
    out.insert("sidecar-messages.json".to_string(), pretty(&Value::Array(sample_messages())));
    out.insert(
        "constants.json".to_string(),
        pretty(&json!({
            "protocolVersion": PROTOCOL_VERSION,
            "heartbeatMs": HEARTBEAT_MS,
            "policyReplyTimeoutMs": POLICY_REPLY_TIMEOUT_MS,
            "leaseTtlMs": LEASE_TTL_MS,
            "batchMaxEvents": BATCH_MAX_EVENTS,
            "batchMaxMs": BATCH_MAX_MS,
            "cancelSoftMs": CANCEL_SOFT_MS,
            "cancelTermMs": CANCEL_TERM_MS,
            "allKinds": ALL_KINDS,
            "bypassKeeps": crate::policy::BYPASS_KEEPS,
            "sdkToolCoverage": crate::policy::SDK_TOOL_COVERAGE.iter().map(|(input, tool, kind)| json!({"input": input, "tool": tool, "kind": kind})).collect::<Vec<_>>(),
        })),
    );
    out
}

/// Writes everything under `root` (the `packages/protocol` directory).
pub fn export_all(root: &Path) -> io::Result<()> {
    let generated = root.join("src/generated");
    let fixtures = root.join("fixtures");
    std::fs::create_dir_all(&generated)?;
    std::fs::create_dir_all(&fixtures)?;
    for (stem, text) in typescript_files() {
        std::fs::write(generated.join(format!("{stem}.ts")), text)?;
    }
    for (name, text) in fixture_files() {
        std::fs::write(fixtures.join(name), text)?;
    }
    Ok(())
}
