// Generated by `pnpm bindings` from crates/files/src/types.rs. Do not edit.
/* eslint-disable */
// This file has been generated by Specta. Do not edit this file manually.
export type BranchList = {
	local: string[],
	remote: string[],
	/**  `None` on a detached HEAD. */
	current: string | null,
	upstream?: string | null,
	ahead: number,
	behind: number,
};

export type DirEntry = {
	name: string,
	kind: FileKind,
	size?: number | null,
	/**  Matched by .gitignore. */
	ignored?: boolean,
	/**  Secret or generated file the IDE never opens (same guard as the commit panel). */
	neverRead?: boolean,
	/**  One-letter porcelain status ("M", "A", "D", "U" or "?"); a directory shows the strongest status below it. */
	gitStatus?: string | null,
};

/**  How the bytes of a file map to text. Writing back with the same value keeps the file's encoding. */
export type Encoding = "utf8" | "utf8Bom" | "utf16le" | "utf16be" | 
/**  Fallback for bytes that are not UTF-8; every byte maps to the code point of the same value. */
"latin1" | 
/**  ISO-8859-2 (Central European, Hungarian); guessed for non-UTF-8 files with double-acute letters. */
"latin2" | 
/**  Windows-1250 (Central European); guessed for non-UTF-8 files with bytes in 0x80..=0x9F. */
"windows1250";

export type Eol = "lf" | "crlf" | "mixed" | "none";

export type FileChangeKind = "created" | "changed" | "deleted";

export type FileChanged = {
	repoId: string,
	path: string,
	kind: FileChangeKind,
};

export type FileKind = "file" | "dir" | "symlink";

export type FileRead = {
	/**  Absent for binary, too large or guarded files. */
	text?: string | null,
	binary: boolean,
	tooLarge: boolean,
	size: number | null,
	mtimeMs: number | null,
	eol: Eol,
	encoding: Encoding,
	guard: GuardState,
};

export type GuardState = "ok" | "neverAdd" | "secret" | "tooLarge" | "sensitive";

export type RollbackResult = {
	/**  Folder holding the patch of the discarded tracked changes and the moved untracked files. */
	backupPath: string,
};

export type SearchBatch = {
	searchId: string,
	hits: SearchHit[],
	/**  The last batch of a search carries `done` (also sent for a cancelled search). */
	done: boolean,
	/**  The hit limit was reached; the search stopped early. */
	truncated?: boolean,
	/**  Why a repo (or the whole search) could not be searched, e.g. an invalid regex. */
	error?: string | null,
	/**  A one-line hint for the user, sent with the last batch: ripgrep is not installed and `git grep` ran instead. */
	notice?: string | null,
};

export type SearchHit = {
	repoId: string,
	path: string,
	/**  1-based. */
	line: number,
	/**  1-based column (in characters) of the match start. */
	col: number,
	preview: string,
};

export type SearchOptions = {
	/**  Defaults to every repo of the workspace. */
	repoIds?: string[] | null,
	regex?: boolean,
	caseSensitive?: boolean,
	/**  Path glob limiting the files searched. */
	glob?: string | null,
};

export type SearchStarted = {
	searchId: string,
};

export type StashEntry = {
	index: number,
	message: string,
	branch?: string | null,
	createdMs: number | null,
};

export type SwitchOutcome = {
	repoId: string,
	status: SwitchStatus,
	code?: string | null,
	error?: string | null,
};

export type SwitchStatus = "switched" | 
/**  The repo has no such branch (or is already on it). */
"skipped" | "failed";

export type WriteResult = {
	mtimeMs: number | null,
};
