// Generated by `pnpm bindings` from crates/graph/src/types.rs. Do not edit.
/* eslint-disable */
// This file has been generated by Specta. Do not edit this file manually.
/**  The status-bar / inline blame of the line under the caret. */
export type BlameCaret = {
	line: number,
	oid: string,
	shortOid: string,
	author: string,
	authorEmail: string,
	dateMs: number,
	/**  "3 days ago"; "Not committed yet" for an uncommitted line. */
	relativeTime: string,
	subject: string,
	uncommitted: boolean,
};

export type BlameLine = {
	/**  1-based. */
	line: number,
	oid: string,
	author: string,
	authorEmail: string,
	dateMs: number,
	/**  Subject of the commit that last touched the line. */
	summary: string,
	text: string,
	/**  The root of a shallow or limited history (`^` in plain blame). */
	boundary: boolean,
	/**  Changed in the working tree and not committed yet. */
	uncommitted: boolean,
};

export type BranchCell = {
	exists: boolean,
	current: boolean,
	upstream?: string | null,
	ahead: number,
	behind: number,
	/**  The upstream branch was deleted on the remote. */
	gone: boolean,
};

export type BranchMatrix = {
	repos: RepoBranchInfo[],
	/**  Sorted by name. */
	branches: BranchRow[],
};

export type BranchRow = {
	name: string,
	cells: { [key in string]: BranchCell },
	/**  The branch exists in every repo of the matrix. */
	inAll: boolean,
};

export type Bundle = {
	id: string,
	name: string,
	source: BundleSource,
	branch?: string | null,
	createdMs: number,
	repoIds: string[],
	commits: BundleCommit[],
};

export type BundleCommit = {
	repoId: string,
	oid: string,
	shortOid: string,
	subject: string,
	dateMs: number,
	/**  No branch or tag reaches the commit any more (rewritten by a rebase or amend). */
	missing: boolean,
};

export type BundleLink = {
	repoId: string,
	oid: string,
};

export type BundleSource = 
/**  Linked by the IDE when one coordinated commit created the commits. */
"recorded" | 
/**  Same subject in several repos within a time window. */
"heuristic";

export type ChangedPath = {
	path: string,
	origPath?: string | null,
	kind: FileKind,
	/**  `None` for binary files. */
	additions?: number | null,
	deletions?: number | null,
	binary: boolean,
};

export type CommitDetail = {
	repoId: string,
	oid: string,
	shortOid: string,
	parents: string[],
	subject: string,
	/**  The full message. */
	message: string,
	author: string,
	authorEmail: string,
	dateMs: number,
	refs: string[],
	decorations: RefDecoration[],
	/**  Against the first parent (the empty tree for a root commit). */
	files: ChangedPath[],
	additions: number,
	deletions: number,
};

export type DraftSource = 
/**  Derived from the paths and stats only. */
"template" | 
/**  Written by the utility model and validated. */
"model";

/**  The only error type of the engine facade; serialised as-is to the UI. */
export type EngineError = {
	code: string,
	message: string,
	detail?: string | null,
};

export type FileKind = "added" | "modified" | "deleted" | "renamed" | "copied" | "typeChange";

/**
 *  One commit of the log. `lane`, `color`, `edges` and `width` describe the drawing of the repo's own graph; in a
 *  multi-repo timeline every repo has its own lane space and the row is tinted by `repoId`'s stripe.
 */
export type GraphRow = {
	repoId: string,
	oid: string,
	shortOid: string,
	parents: string[],
	subject: string,
	author: string,
	authorEmail: string,
	dateMs: number,
	/**  Names of `decorations`, for simple chips. */
	refs: string[],
	decorations: RefDecoration[],
	lane: number,
	color: number,
	edges: LaneEdge[],
	/**  Number of lanes this row occupies (the drawing needs `width * laneWidth` pixels). */
	width: number,
};

export type InProgressOp = "none" | "rebase" | "cherryPick";

export type LaneEdge = {
	from: number,
	to: number,
	/**  Stable colour index of the line; the UI maps it onto a palette modulo its size. */
	color: number,
	kind: LaneEdgeKind,
};

/**
 *  `up`: a line from the top of the row at lane `from` into the node at lane `to` (a child arriving or a lane
 *  merging). `down`: from the node (`from`) to the bottom of the row at lane `to` (a parent). `through`: a lane
 *  that only passes the row (`from == to`).
 */
export type LaneEdgeKind = "up" | "down" | "through";

export type LogFilters = {
	/**  A single ref to walk; default: every branch, remote branch, tag and `HEAD`. */
	branch?: string | null,
	author?: string | null,
	/**  Case-insensitive substring of the commit message. */
	text?: string | null,
	path?: string | null,
	sinceMs?: number,
	untilMs?: number,
};

export type LogPage = {
	/**  Newest first by commit time across repos; within a repo in `--topo-order`. */
	rows: GraphRow[],
	/**  Opaque; pass it back (with the same filters) for the next page. Absent on the last page. */
	nextCursor?: string | null,
	repos: RepoStripe[],
};

export type MessageCheck = {
	/**  No errors (warnings do not count). */
	ok: boolean,
	header?: ParsedHeader | null,
	issues: MessageIssue[],
};

export type MessageDraft = {
	message: string,
	source: DraftSource,
	/**  Why the model was not used, or what it got wrong. */
	note?: string | null,
	issues: MessageIssue[],
};

export type MessageIssue = {
	severity: Severity,
	/**  Stable id such as `header.format` or `extended.missingHungarian`. */
	code: string,
	message: string,
};

export type MessageStyle = 
/**  `type(scope): description`, optional body. */
"conventional" | 
/**  Conventional header plus the `Extended English:` and `Magyar bővített leírás:` paragraphs. */
"extended";

/**  Result of a rebase / cherry-pick call and of `rebaseState`. */
export type OpOutcome = {
	repoId: string,
	kind: InProgressOp,
	status: OpStatus,
	/**  1-based step being applied, 0 when unknown. */
	step: number,
	total: number,
	conflictFiles: string[],
	/**  `HEAD` after the call. */
	head?: string | null,
	/**  What git printed when it stopped. */
	message?: string | null,
};

export type OpStatus = 
/**  Nothing in progress. */
"idle" | "done" | 
/**  Stopped on unmerged paths: resolve and stage them, then `continue`, or `abort`. */
"conflict" | 
/**  In progress without conflicts (for example a failed hook): `continue` or `abort`. */
"stopped";

export type ParsedHeader = {
	type: string,
	scope?: string | null,
	breaking: boolean,
	description: string,
};

export type RebaseAction = "pick" | "reword" | "squash" | "fixup" | "drop";

/**  Oldest first, like the todo list of `git rebase -i`. */
export type RebasePlan = {
	repoId: string,
	onto: string,
	steps: RebaseStep[],
};

export type RebaseStep = {
	action: RebaseAction,
	/**  Full oid of a commit in `onto..HEAD`. */
	oid: string,
	subject: string,
	/**
	 *  `reword`: the new message (required). `squash`: the final message of the whole chain (optional, default is
	 *  git's combination of the messages). Not allowed on other actions.
	 */
	message?: string | null,
};

/**  One ref pointing at a commit (`--decorate=full`, namespaces stripped). */
export type RefDecoration = {
	name: string,
	kind: RefKind,
	/**  `HEAD` points here (the checked-out branch, or the detached head). */
	current: boolean,
};

export type RefKind = 
/**  A detached `HEAD`. */
"head" | "branch" | "remote" | "tag";

/**  One repo's checked-out branch. */
export type RepoBranchInfo = {
	repoId: string,
	current?: string | null,
	/**  `HEAD` is not on a branch (detached or unborn). */
	detached: boolean,
	upstream?: string | null,
	ahead: number,
	behind: number,
	gone: boolean,
};

export type RepoOpResult = {
	repoId: string,
	ok: boolean,
	error?: EngineError | null,
};

/**  Colour and label of a repo, for the stripe in the interleaved timeline. */
export type RepoStripe = {
	repoId: string,
	name: string,
	color: string,
	badge: string,
};

/**  `applied` is false when a preflight failed in any repo: nothing was changed, `repos` tells why. */
export type SameBranchResult = {
	branch: string,
	applied: boolean,
	repos: RepoOpResult[],
};

export type SelectedPath = {
	path: string,
};

export type Severity = "error" | "warning";
