// Generated by `pnpm bindings` from crates/happy/src/types.rs. Do not edit.
/* eslint-disable */
// This file has been generated by Specta. Do not edit this file manually.
/**  Attachment metadata only: files are not downloaded by the chat (no remote content in the webview). */
export type ChatAttachment = {
	name: string,
	mimeType: string,
	size: number,
};

export type ChatChannel = {
	id: string,
	kind: ChatKind,
	name: string,
	unreadCount: number,
	mentionCount: number,
	muted: boolean,
	notifyLevel: NotifyLevel,
	lastMessageAtMs?: number | null,
	topic: string,
	description: string,
	memberCount: number,
	archived: boolean,
	starred: boolean,
	/**  False for a channel seen through `browse` that the user has not joined. */
	isMember: boolean,
	/**  The user's role in the channel (`admin`, `member`), when a member. */
	role?: string | null,
	/**  The other people of a direct or group channel. */
	peers: ChatPerson[],
	lastPreview?: string | null,
	lastSender?: string | null,
};

/**  Event `happy:chat`. Deltas only: the webview subscribes and applies them to what `chatOpen` returned. */
export type ChatEvent = 
/**  Channel list or counters changed. */
{ type: "summary"; summary: ChatSummary } | 
/**
 *  `notify` is true when the message deserves a toast: someone else's, not in the channel the user is looking at,
 *  and allowed by the channel's `notifyLevel` (`none` never, `mentions` only mentions and direct messages, `all`
 *  everything; a muted channel only for mentions).
 */
{ type: "message"; channelId: string; message: ChatMessage; change: MessageChange; notify: boolean } | 
/**  Who is typing in a channel right now (expires by itself after about 5 s). */
{ type: "typing"; channelId: string; names: string[] } | 
/**  The socket state changed. */
{ type: "link"; link: ChatLink };

export type ChatKind = 
/**  A public channel (`type: "public"`). */
"channel" | "private" | "direct" | 
/**  A group conversation (a direct channel with several other people). */
"group" | "record" | "customer";

/**  The shared socket, as the chat UI needs it: `reconnecting` makes the chip say so and the poll cadence faster. */
export type ChatLink = "off" | "connecting" | "live" | "reconnecting";

/**  A member of a channel (the members panel). */
export type ChatMember = {
	id: string,
	name: string,
	email?: string | null,
	/**  `admin` or `member`. */
	role: string,
	online: boolean,
	portal: boolean,
};

/**  Plain text only: no HTML, no remote images (the webview renders links itself and opens them through Rust). */
export type ChatMessage = {
	id: string,
	channelId: string,
	clientMessageId?: string | null,
	senderId: string,
	senderName: string,
	text: string,
	createdAtMs: number,
	edited: boolean,
	deleted: boolean,
	/**  A system line ("X joined"), shown muted. */
	system: boolean,
	mine: boolean,
	/**  The message mentions the current user. */
	mentionsMe: boolean,
	sendState: SendState,
	/**  Why a `failed` send failed (`INSUFFICIENT_CREDITS`, `offline`, ...). */
	errorCode?: string | null,
	/**  `text`, `system`, `meeting` or `record`. */
	kind: string,
	/**  Set on a thread reply: the id of the root message. Replies are never shown inline in the channel. */
	threadRoot?: string | null,
	/**  On a root message: how many replies, who replied and when last. */
	replyCount: number,
	lastReplyAtMs?: number | null,
	replyUsers: ChatPerson[],
	reactions: ChatReaction[],
	attachments: ChatAttachment[],
	pinned: boolean,
};

export type ChatPerson = {
	id: string,
	name: string,
	detail?: string | null,
};

export type ChatReaction = {
	emoji: string,
	count: number,
	/**  The current user reacted with it. */
	mine: boolean,
};

/**  `GET /api/chat/search` (server-side, up to 30 each). */
export type ChatSearch = {
	messages: SearchHit[],
	channels: ChatChannel[],
	people: ChatPerson[],
};

/**
 *  The channel list with counters. `credits` and `sendCost` are store credits: every send spends `sendCost` on the real
 *  service (the plan says 0.02, unverified), so the UI shows a hint and a blocked state when `creditsEmpty`.
 */
export type ChatSummary = {
	channels: ChatChannel[],
	unreadTotal: number,
	mentionTotal: number,
	/**  How many threads have replies the user has not seen (server-driven, from `GET /api/chat/threads?unread=true`). */
	threadUnread: number,
	/**  What the store's settings let this user do (bootstrap `permissions`). */
	canCreateChannel: boolean,
	canManageChannels: boolean,
	credits?: number | null,
	sendCost: number | null,
	/**  The last send was answered with 402, or the bootstrap says the balance is 0. Cleared by the next good bootstrap or send. */
	creditsEmpty: boolean,
	link: ChatLink,
	/**  The last bootstrap failed (offline/backoff): the data may be out of date. */
	stale: boolean,
	/**  A bootstrap has succeeded since the provider started. */
	loaded: boolean,
};

/**  A partial update of [`HappyConfig`]; an empty `customBaseUrl` clears it. */
export type ConfigPatch = {
	master?: boolean | null,
	env?: Env | null,
	customBaseUrl?: string | null,
	timer?: PrefsPatch | null,
	meet?: PrefsPatch | null,
	chat?: PrefsPatch | null,
	notifications?: PrefsPatch | null,
	tasks?: PrefsPatch | null,
};

/**
 *  Result of `testConnection` and `saveToken`: the current user from `GET /api/user/me` and, per provider, whether the
 *  token may use it.
 */
export type ConnectionTest = {
	ok: boolean,
	user?: UserInfo | null,
	message?: string | null,
	providers: ProviderCheck[],
};

/**  Which Happy backend the connection talks to. Each environment has its own token slot. */
export type Env = "production" | "sandbox" | "custom";

/**  What is persisted in `settings.json` under `happy`. No secrets. */
export type HappyConfig = {
	/**  The master switch: off stops every provider without touching their own switches. */
	master: boolean,
	env: Env,
	/**  Only used with `env: custom`: https, or http on a loopback host. */
	customBaseUrl?: string | null,
	timer: ProviderPrefs,
	meet: ProviderPrefs,
	/**  Team chat (Beta 2): REST plus the shared Socket.IO connection. Sending costs store credits on the real service. */
	chat: ProviderPrefs,
	/**  Notifications inbox: badge, list and mark-read (polled, no socket). */
	notifications: ProviderPrefs,
	/**  My tasks: the list by status, with the timer and agent shortcuts. */
	tasks: ProviderPrefs,
};

/**  Event `happy:state` carries the same shape. */
export type HappyStatus = {
	config: HappyConfig,
	/**  The resolved base URL (host only is shown in the UI), `None` when a custom URL is invalid. */
	baseUrl?: string | null,
	tokenSaved: boolean,
	user?: UserInfo | null,
	validatedAtMs?: number | null,
	/**  Set after a 401: the whole connection is stopped and the UI shows a persistent banner until a new token is saved. */
	signedOut?: LastError | null,
	providers: ProviderStatus[],
};

export type LastError = {
	/**  The server's `code` when it sent one (`DEVICE_LOGGED_OUT`, `INSUFFICIENT_CREDITS`), else a short name. */
	code: string,
	/**  Already redacted. */
	message: string,
	atMs: number,
};

/**  Event `happy:meetings` carries the same shape. */
export type MeetView = {
	meetings: Meeting[],
	stale: boolean,
};

/**  Never carries a join URL: joining is a Rust-side call that opens the browser. */
export type Meeting = {
	id: string,
	title: string,
	channel?: string | null,
	status: MeetingStatus,
	startMs?: number | null,
	participants: number,
	host?: string | null,
	/**  Guests waiting in the lobby (`chat:meeting:lobby`); only set while someone waits. */
	waiting?: number | null,
};

export type MeetingStatus = "live" | "scheduled";

export type MessageChange = "new" | "updated" | "deleted" | 
/**  The optimistic message was replaced by the server's copy. */
"replaced" | 
/**  A send failed (the message stays visible with Retry). */
"failed";

/**
 *  Oldest first. `cursor` is the id to pass as `before` for the next older page, `None` at the start of history.
 *  `hasNewer` and `anchorId` are set by an `around` window (a jump to a message).
 */
export type MessagePage = {
	channelId: string,
	messages: ChatMessage[],
	hasMore: boolean,
	cursor?: string | null,
	hasNewer: boolean,
	anchorId?: string | null,
};

export type NotificationItem = {
	id: string,
	title: string,
	body?: string | null,
	/**  The server's category (`mention`, `task`, `deploy`, ...) when it sends one. */
	kind?: string | null,
	createdAtMs?: number | null,
	read: boolean,
	/**  Chat notifications carry where they point (`metadata`): the channel, the message and the thread root of a reply. */
	channelId?: string | null,
	messageId?: string | null,
	threadRoot?: string | null,
	/**  `chat.message.direct|mention|channel|thread`, ... */
	eventKey?: string | null,
};

/**
 *  Event `happy:notifications` carries the same shape. `loaded` is false until the list was fetched once; the badge count
 *  alone is known earlier.
 */
export type NotificationsView = {
	items: NotificationItem[],
	unread: number,
	loaded: boolean,
	/**  Two polls in a row failed: the numbers may be out of date. */
	stale: boolean,
};

/**  The member's notification preference per channel; drives which messages ask for a toast. */
export type NotifyLevel = "all" | "mentions" | "none";

export type PrefsPatch = {
	enabled?: boolean | null,
	showInStatusBar?: boolean | null,
	allowActions?: boolean | null,
};

/**  A project the picker search found; its tasks come back as [`Trackable`] rows grouped under `project`. */
export type ProjectHit = {
	id: string,
	title: string,
	code?: string | null,
	customer?: string | null,
};

export type ProviderCheck = {
	id: string,
	allowed: boolean,
	hint?: string | null,
};

export type ProviderPrefs = {
	enabled: boolean,
	showInStatusBar: boolean,
	/**  Mutating calls (start/stop, join) are refused while this is off. */
	allowActions: boolean,
};

/**
 *  `off -> waitingForToken -> probing -> ready <-> degraded`, side exits `notPermitted` (403: no polling until a manual
 *  test or a new token), `signedOut` (401: shared by the whole connection) and `error`. The switch stores the intent,
 *  the state says what actually runs.
 */
export type ProviderState = "off" | "waitingForToken" | "probing" | "ready" | "degraded" | "notPermitted" | "signedOut" | "error";

export type ProviderStatus = {
	/**  `timer`, `meet` or `chat`. */
	id: string,
	state: ProviderState,
	lastError?: LastError | null,
};

export type SearchHit = {
	message: ChatMessage,
	channelName: string,
};

/**
 *  `pending` and `failed` only exist for the user's own optimistic sends; the socket echo (same `clientMessageId`)
 *  replaces them with a `sent` message.
 */
export type SendState = "sent" | "pending" | "failed";

export type TaskItem = {
	id: string,
	/**  Human key such as `HP-142` or a number, when the server has one. */
	key?: string | null,
	title: string,
	/**  The status id (matches `TaskStatus.id`), or the status name when the server only sends that. */
	status: string,
	project?: string | null,
	projectId?: string | null,
	priority?: string | null,
	dueMs?: number | null,
	description?: string | null,
	/**  A repository named by the server, when it sends one; the IDE maps projects to repositories itself otherwise. */
	repo?: string | null,
};

/**  `timer.search`: matching projects, and tasks (each with its project title) of the matches. */
export type TaskSearch = {
	projects: ProjectHit[],
	tasks: Trackable[],
};

export type TaskStatus = {
	id: string,
	name: string,
	order: number,
	/**  A finished status (done, closed, ...): the list hides these by default. */
	done: boolean,
};

/**  Event `happy:tasks` carries the same shape. */
export type TasksView = {
	tasks: TaskItem[],
	statuses: TaskStatus[],
	loaded: boolean,
	stale: boolean,
};

/**  One row of the "Threads" list. */
export type ThreadSummary = {
	root: ChatMessage,
	channelId: string,
	channelName: string,
	channelKind: ChatKind,
	replyCount: number,
	lastReplyAtMs?: number | null,
	unreadCount: number,
};

/**  A thread: the root message and its replies, oldest first. */
export type ThreadView = {
	channelId: string,
	root: ChatMessage,
	replies: ChatMessage[],
};

export type TimeEntry = {
	id: string,
	title: string,
	project?: string | null,
	startedAtMs: number,
	/**  `None` while the entry is still running. */
	endedAtMs?: number | null,
	seconds: number,
	/**  Closed by the server after being left open (shown as 0 s and labelled). */
	abandoned: boolean,
};

/**  Settled seconds of the current day, week and month (`/api/projects/time-entries/summary`); the running entry is not in it. */
export type TimeTotals = {
	daySec: number,
	weekSec: number,
	monthSec: number,
};

export type TimerPhase = "idle" | "running" | "paused" | "break";

/**
 *  One shape for both server payloads (the `running-timer` entry and the widget's timer state). The clock ticks in the
 *  webview from `startedAtMs`, `accumulatedSec` and `offsetMs` (server time minus local time).
 */
export type TimerView = {
	phase: TimerPhase,
	/**  `project` or `workOrder`; empty while idle. */
	kind: string,
	targetId: string,
	taskId?: string | null,
	title: string,
	project?: string | null,
	startedAtMs: number,
	/**  Seconds counted before `startedAtMs` (pauses excluded); the whole value while paused. */
	accumulatedSec: number,
	canBreak: boolean,
	offsetMs: number,
	/**  Two polls in a row failed: the clock keeps running but the state may be out of date. */
	stale: boolean,
};

export type TodayView = {
	entries: TimeEntry[],
	totalSeconds: number,
	/**  More rows exist than the paging cap loaded (the oldest ones are missing). */
	truncated: boolean,
};

export type Trackable = {
	kind: string,
	id: string,
	taskId?: string | null,
	title: string,
	project?: string | null,
};

export type UserInfo = {
	id: string,
	name: string,
	roles: string[],
	restaurantId?: string | null,
	restaurantName?: string | null,
};
