// Generated by `pnpm bindings` from crates/mcp/src/types.rs. Do not edit.
/* eslint-disable */
// This file has been generated by Specta. Do not edit this file manually.
export type McpCodeFile = {
	/**  Escaped like `commandLine`. */
	path: string,
	/**  The first 12 hex characters of the digest (or `unresolved` / `absent`). */
	sha256: string,
};

export type McpImportEntry = {
	/**  The original name in the file. */
	key: string,
	suggestedName: string,
	/**  `stdio`, `http` or `unknown`. */
	transport: string,
	commandLine?: string | null,
	urlHost?: string | null,
	/**  NAMES ONLY, never values. */
	env: McpImportVar[],
	headers: McpImportVar[],
	issues: McpImportIssue[],
	importable: boolean,
	conflict: boolean,
};

/**  A closed set the UI words. */
export type McpImportIssue = "unsupportedTransport" | "badName" | "nameTaken" | "secretInArgs" | "secretInUrl" | "unresolvedRef" | "badCommand" | "badVar" | "badChars" | "relativePath" | "tooMany";

export type McpImportPick = {
	key: string,
	name: string,
	/**  Overwrite the server of the same name. */
	replace: boolean,
};

export type McpImportPreview = {
	importId: string,
	/**  Basename only. */
	fileName: string,
	entries: McpImportEntry[],
	/**  Top-level keys that were not objects. */
	skippedKeys: number,
	expiresAt: number,
};

export type McpImportResult = {
	imported: McpImportedServer[],
	skipped: McpImportSkipped[],
};

export type McpImportSkipped = {
	key: string,
	reason: string,
};

export type McpImportVar = {
	name: string,
	secret: boolean,
};

export type McpImportedServer = {
	key: string,
	id: string,
};

/**  What the jail says about starting MCP servers (`readOnly` refuses, `e2e` allows loopback http only). */
export type McpJail = "off" | "readOnly" | "e2e";

export type McpList = {
	schema: number,
	servers: McpServerView[],
	workspace: McpWorkspaceView,
	secrets: McpSecretsView,
	jail: McpJail,
	readOnlyReason?: string | null,
	problems: McpProblem[],
};

/**  What the user decided for a tool (or a server's default). `ask` is the default of a new server. */
export type McpPolicy = "ask" | "allow" | "deny";

export type McpPolicyPatch = {
	defaultPolicy?: McpPolicy | null,
	tools?: McpToolPatch[] | null,
};

export type McpProblem = {
	index: number,
	reason: string,
};

export type McpRunServer = {
	id: string,
	name: string,
	transport: McpTransport,
	/**  The effective default for the workspace (2.5). */
	defaultOn: boolean,
	available: boolean,
	/**  `needsConfirm`, `secretMissing`, `invalid`, `unsupportedProvider`, `unsupportedAuth`, `readOnlyJail` or `unsupported`. */
	unavailable?: string | null,
	toolCount: number,
	readOnlyCount: number,
	defaultPolicy: McpPolicy,
	/**  The default or any tool is deny. */
	hasDenied: boolean,
	/**  A stdio server with at least one secret env slot (7.7 warns in Automatic and Bypass, 6.4 point 3). */
	hasSecretEnv: boolean,
	/**  Listed tools that are not read-only and not deny: they run without a prompt in Automatic and Bypass. */
	exposedCount: number,
};

export type McpSaveInput = {
	id?: string | null,
	name: string,
	transport: McpTransport,
	command?: string | null,
	args?: string[] | null,
	url?: string | null,
	env?: McpVarInput[] | null,
	headers?: McpVarInput[] | null,
	enabled: boolean,
};

export type McpSecretPresence = {
	serverId: string,
	/**  `env:NAME` or `hdr:Name`. */
	slot: string,
	present: boolean,
};

export type McpSecretsView = {
	/**  `keychain` or `memory`. */
	backend: string,
	degraded: boolean,
	message: string | null,
};

export type McpServerInfoView = {
	name: string,
	version: string,
	protocolVersion: string,
};

export type McpServerView = {
	id: string,
	name: string,
	transport: McpTransport,
	command?: string | null,
	args: string[],
	url?: string | null,
	env: McpVarView[],
	headers: McpVarView[],
	enabled: boolean,
	defaultPolicy: McpPolicy,
	tools: McpToolView[],
	toolsTestedAt: number | null,
	toolsStale: boolean,
	/**  Overrides for tools the last Test did not list. */
	staleToolPolicies: McpStalePolicy[],
	serverInfo: McpServerInfoView | null,
	state: McpState,
	/**  The Keychain proof equals `confirmHash`. */
	confirmed: boolean,
	/**  `origin == "import"`: the confirm dialog adds a warning line about hidden values. */
	imported: boolean,
	/**  What the user must send to `mcp_confirm`; the dialog shows exactly what it covers. */
	confirmHash: string,
	/**  Display form of command + args on ONE line (every non-printable or non-ASCII character escaped); never run through a shell. */
	commandLine?: string | null,
	/**  The confirm dialog's form: one entry per argument, escaped, never truncated, padding spaces shown as U+2423. */
	argsDisplay: string[],
	/**  http: the host as stored (ASCII, punycode form). */
	urlHost?: string | null,
	/**  stdio: the files the confirmation vouches for. */
	codeFiles: McpCodeFile[],
	/**  An unpinned package runner: the code is fetched at every start. */
	fetchesCode: boolean,
	createdAt: number | null,
	updatedAt: number | null,
};

export type McpStalePolicy = {
	tool: string,
	policy: McpPolicy,
};

/**  Why a server cannot be tested or started right now (the first applicable one). */
export type McpState = "ready" | "needsConfirm" | "secretMissing" | "invalid" | "unsupported";

export type McpTestCapabilities = {
	tools: boolean,
	resources: boolean,
	prompts: boolean,
};

export type McpTestError = {
	code: string,
	message: string,
	detail?: string | null,
};

export type McpTestReport = {
	ok: boolean,
	ms: number | null,
	protocolVersion?: string | null,
	serverInfo?: McpTestServerInfo | null,
	capabilities?: McpTestCapabilities | null,
	tools: McpToolView[],
	toolCount: number,
	truncated: boolean,
	/**  Keys, versus the previous successful Test. */
	newTools: string[],
	removedTools: string[],
	/**  Keys this Test seeded with `deny` (4.4). */
	blockedByDefault: string[],
	fetchesCode: boolean,
	instructions?: string | null,
	instructionsChanged?: boolean | null,
	stderrTail?: string | null,
	error?: McpTestError | null,
};

export type McpTestServerInfo = {
	name: string,
	version: string,
};

export type McpToolPatch = {
	tool: string,
	/**  `null` removes the override. */
	policy: McpPolicy | null,
	acknowledgeBlocked?: boolean | null,
};

export type McpToolView = {
	name: string,
	key: string,
	title?: string | null,
	description?: string | null,
	readOnly: boolean,
	readOnlyHint: boolean | null,
	destructiveHint: boolean | null,
	/**  The user's override. */
	policy: McpPolicy | null,
	effectivePolicy: McpPolicy,
	collision?: boolean | null,
	/**  The key or the destructive hint matches the git/deploy write vocabulary (4.4). */
	blockedByDefault: boolean,
	/**  The current override is the Test's seed, not the user's choice. */
	seeded: boolean,
};

export type McpTransport = "stdio" | "http";

export type McpVarInput = {
	name: string,
	secret: boolean,
	/**  Plain variables only. */
	value?: string | null,
	/**  WRITE-ONLY. Present = set or replace the Keychain item. Absent on an existing secret slot = keep it. */
	secretValue?: string | null,
};

export type McpVarView = {
	name: string,
	secret: boolean,
	/**  Plain variables only; a secret value is never sent. */
	value?: string | null,
	/**  Secret: an item exists in the Keychain; plain: true. */
	present: boolean,
};

export type McpWorkspaceOverride = {
	serverId: string,
	/**  `on` or `off` (`inherit` has no entry). */
	state: McpWorkspaceState,
};

/**  The per-workspace tri-state (`inherit` removes the entry). */
export type McpWorkspaceState = "inherit" | "on" | "off";

export type McpWorkspaceView = {
	id: string | null,
	overrides: McpWorkspaceOverride[],
};
