// Generated by `pnpm bindings` from crates/mongo/src/api.rs. Do not edit.
/* eslint-disable */
// This file has been generated by Specta. Do not edit this file manually.
export type AiAsk = {
	tab: string,
	connection: string,
	db: string,
	collection: string,
	question: string,
	editor?: AiEditor | null,
	thinkHarder?: boolean | null,
	refreshSchema?: boolean | null,
	/**  `mongo_ai_explain` only: the plan lines the UI shows. */
	plan?: string[] | null,
	/**  The caller's UTC offset in minutes and zone name (the generic preset words dates in them; D24). */
	utcOffsetMin?: number | null,
	tzName?: string | null,
};

export type AiCapabilities = {
	node: boolean,
	claudeCli: boolean,
	script: boolean,
};

export type AiDraft = {
	/**  The collection the draft is for. It differs from the tab's collection when the question is about another one. */
	collection: string,
	filter: string,
	projection: string,
	sort: string,
	limit?: number | null,
	explanation: string,
	modelNote: string,
	assumptions: string[],
	warnings: string[],
	plan?: AiPlan | null,
	indexSuggestion?: string | null,
	changedFields: string[],
	extraConfirm: boolean,
};

/**
 *  The AI half of the gateway (`mongo_ai_*`). The wire shapes are `ui/src/ipc/mongoAi.ts`. Nothing here carries a document
 *  or a secret: a draft is text that the user reviews and runs through `mongo_run`.
 */
export type AiEditor = {
	filter: string,
	projection?: string,
	sort?: string,
	limit?: number | null,
	returned?: number | null,
};

export type AiExplanation = {
	text: string,
};

/**  P0 (nothing leaves the machine) and P1 (schema only). Samples (P2/P3) are M2 and cannot be expressed here. */
export type AiMode = "off" | "schemaOnly" | 
/**  Schema plus the value sets of low-cardinality, non-PII string fields (explicit consent, shown in the preview). */
"schemaEnums";

export type AiPayload = {
	/**  `schemaOnly` (P1) or `schemaEnums` (P1 plus the filtered value sets of low-cardinality fields). */
	mode: string,
	/**  The exact bytes that would reach the model, after the PII filter. */
	text: string,
	bytes: number,
	tokensEstimate: number,
	keptNames: string[],
	replacedNames: number,
	excludedFields: number,
	maskedLiterals: number,
	notes: string[],
};

export type AiPlan = {
	collscan: boolean,
	indexNames: string[],
	estimatedDocs?: number | null,
};

/**  Per-profile AI wording. Both lists are signed (they can only be loosened through a typed confirmation). */
export type AiPrefs = {
	denyFields?: string[],
	glossary?: GlossaryPair[],
};

export type AiResult = {
	/**  `ready`, `needsClarification` or `failed`. */
	status: string,
	draft?: AiDraft | null,
	clarification?: string | null,
	message: string,
	problems: string[],
	repairs: number,
	notes: string[],
	model: string,
	tookMs: number,
};

export type AllowedHost = {
	host: string,
	port: number,
};

export type AuthMechanism = "none" | 
/**  SCRAM, negotiated by the driver. */
"default" | "scramSha1" | "scramSha256" | "x509" | "plain";

export type AuthSpec = {
	mechanism?: AuthMechanism,
	username?: string | null,
	/**  The authentication database (`$external` for X.509 and PLAIN). */
	source?: string | null,
	savePassword?: boolean,
};

export type CancelView = {
	cancelled: boolean,
	/**  The server confirmed the kill of our own operation (otherwise `maxTimeMS` is the backstop). */
	killed: boolean,
};

export type Compressor = "zstd" | "zlib" | "snappy";

export type ConnSpec = {
	scheme?: Scheme,
	hosts?: HostPort[],
	database?: string | null,
	auth?: AuthSpec,
	tls?: TlsSpec,
	topology?: TopologySpec,
	compressors?: Compressor[],
	timeouts?: Timeouts,
	appName?: string | null,
	extra?: ExtraOption[],
	tunnel?: Tunnel,
};

export type ConnectionView = {
	id: string,
	name: string,
	serverVersion: string,
	topology: string,
	pingMs: number,
	effectiveLevel: EffectiveLevel,
	environment: Environment,
	readOnly: boolean,
	readPreference: ReadPreference,
	/**  The result of the role probe, always shown. */
	role: RoleChip,
	/**  The user can write (or the probe could not tell): "read-only here is an app-level guard", one level riskier. */
	roleElevated: boolean,
	/**  The connection is TLS-protected. */
	tls: boolean,
	tunnel?: TunnelState | null,
	tlsRelax: TlsRelax,
};

/**  A failure as codes and parameters; the UI renders prose from `mongoDiag`. `detail` is scrubbed English raw text. */
export type Diagnosis = {
	class: ErrorClass,
	code: string,
	params: ([string, string])[],
	detail: string,
	retryable: boolean,
};

/**  A one-time ticket for a file the user picked in a native dialog that Rust opened (the webview never sees a path). */
export type DialogHandle = {
	token: string,
	kind: DialogKind,
	/**  The file name only, for display. */
	fileName?: string | null,
};

export type DialogKind = "import" | "export";

/**  Which preset a profile uses for AI wording. A record saved before presets existed has no domain and is read as `Happy`. */
export type Domain = "generic" | "happy";

export type EffectiveLevel = "local" | 
/**  Any non-loopback host (and any +srv host), whatever the user-set tag says. */
"productionLevel";

/**  The user-set label. Cosmetic plus a default: the host rule can raise the level, the tag alone never lowers it. */
export type Environment = "local" | "sandbox" | "production";

export type ErrorClass = "dns" | "network" | "tls" | "auth" | "authz" | "selection" | "tunnel" | "config" | "timeout" | "other";

export type ExtraOption = {
	key: string,
	value: string,
};

/**  One problem found by [`ConnSpec::validate`]. `code` becomes an i18n key; `warning` problems do not block a save. */
export type FieldProblem = {
	path: string,
	code: string,
	warning?: boolean,
};

export type ForgetReport = {
	/**  Fingerprints removed and fingerprints now trusted for the host. */
	old: string[],
	current: string[],
};

export type GlossaryPair = {
	from: string,
	to: string,
};

export type HostKeyStatus = "unknown" | "known" | "changed";

export type HostKeyView = {
	host: string,
	port: number,
	keyType: string,
	/**  `SHA256:...` */
	fingerprint: string,
	status: HostKeyStatus,
};

/**  `Srv`: exactly one host and no port. */
export type HostPort = {
	host: string,
	port?: number | null,
};

export type ImportItem = {
	name: string,
	warnings: Note[],
	/**  Every outbound endpoint (`host:port`): database hosts, bastion, proxy. */
	endpoints: string[],
	needsConfirm: boolean,
};

export type ImportPreview = {
	items: ImportItem[],
	notes: Note[],
};

export type ImportReport = {
	imported: number,
	skipped: number,
	notes: Note[],
};

export type LocalHit = {
	host: string,
	port: number,
};

/**  A code the UI turns into a sentence (`mongoForm`/`mongoDiag` catalogs), with the option it concerns. */
export type Note = {
	code: string,
	option?: string | null,
};

export type Notice = {
	profileId: string,
	message: string,
};

export type PlanView = {
	stages: string[],
	collscan: boolean,
	indexNames: string[],
	engine: string,
	docsExamined?: number | null,
	keysExamined?: number | null,
	nReturned?: number | null,
	rejectedPlans: number,
	warnings: string[],
};

/**  A legacy profile converted for review: nothing changes until the user saves it. */
export type ProfileDraft = {
	input: ProfileInput,
	draft?: string | null,
	dropped: Note[],
};

/**
 *  Create or update. `uri` is write-only (it goes to the Keychain through the secret store). Raising safety needs
 *  nothing; **lowering** it (read-only off, AI on, level override, Production tag lowered) needs `confirm` equal to the
 *  profile name, and the override needs the typed host.
 */
export type ProfileInput = {
	id?: string | null,
	name: string,
	environment: Environment,
	color?: string | null,
	uri?: WireSecret | null,
	/**  `None` keeps the stored value (a new profile starts read-only). */
	readOnly?: boolean | null,
	aiMode?: AiMode | null,
	/**  Empty string clears. */
	tenantLock?: string | null,
	/**  The host name typed by the user; must equal the first non-loopback host of the URI. Empty string clears. */
	levelOverrideHost?: string | null,
	maxTimeMs?: number | null,
	confirm?: string | null,
	/**  The structured connection. `uri` and `spec` together are `mongoInvalid`. */
	spec?: ConnSpec | null,
	/**  Write-only secrets. `None` keeps the stored one while the connection identity is unchanged; `Some("")` clears. */
	password?: WireSecret | null,
	keyPassword?: WireSecret | null,
	sshSecret?: WireSecret | null,
	proxyPassword?: WireSecret | null,
	/**  A draft-vault token (secrets parsed from a pasted string); redeemed by the gateway, never by the profile store. */
	draft?: string | null,
	/**  Empty string clears. */
	group?: string | null,
	favorite?: boolean | null,
	domain?: Domain | null,
	aiPrefs?: AiPrefs | null,
	tlsRelax?: TlsRelax | null,
};

/**  Cosmetic edits that need no re-signing and no typed confirmation. */
export type ProfileMeta = {
	/**  Empty string clears. */
	group?: string | null,
	favorite?: boolean | null,
	color?: string | null,
};

export type ProfileView = {
	id: string,
	name: string,
	environment: Environment,
	color: string,
	readOnly: boolean,
	aiMode: AiMode,
	tenantLock: string | null,
	/**  A typed-host override lowers the host rule for this connection (shown as a chip). */
	levelOverride: boolean,
	/**  Masked display host, computed at save time. Never the URI. */
	host: string,
	hasUri: boolean,
	/**  What the host rule said when the URI was saved. */
	hostLevel: EffectiveLevel,
	/**  `max(tag, host rule)` with the override applied. */
	effectiveLevel: EffectiveLevel,
	readPreference: ReadPreference,
	maxTimeMs: number,
	/**  The structured connection (non-secret: hosts, user names and file paths are in it, passwords never). */
	spec?: ConnSpec | null,
	/**  Saved by an older build as one string: offer "Convert it to fields". */
	legacyUri: boolean,
	/**  The signature check failed: connect and test answer `mongoNeedsReview` until the user saves again. */
	needsReview: boolean,
	hasPassword: boolean,
	hasKeyPassword: boolean,
	hasSshSecret: boolean,
	hasProxyPassword: boolean,
	group?: string | null,
	favorite: boolean,
	domain: Domain,
	aiPrefs: AiPrefs,
	tlsRelax: TlsRelax,
	/**  Milliseconds since the epoch (a JS number; specta refuses 64-bit integers). */
	lastUsedMs?: number | null,
	/**  The connection rendered with the password masked (`user:***@`), empty when it cannot be rendered. */
	uriMasked: string,
};

export type ProxySpec = {
	host: string,
	port: number,
	username?: string | null,
	savePassword?: boolean,
};

export type ReadCommand = { cmd: "listDatabases" } | { cmd: "listCollections"; db: string } | { cmd: "listIndexes"; db: string; collection: string } | { cmd: "find"; db: string; collection: string; filter?: string; projection?: string | null; sort?: string | null; skip?: number | null; limit?: number | null } | { cmd: "aggregate"; db: string; collection: string; pipeline: string } | 
/**  Bounded `countDocuments` (limit + maxTimeMS), or `estimatedDocumentCount` when the filter is empty. */
{ cmd: "count"; db: string; collection: string; filter?: string } | { cmd: "distinct"; db: string; collection: string; field: string; filter?: string } | 
/**  `$sample` of `size` documents (1 to 1000) for the schema digest; the cheap path only when it is the first stage. */
{ cmd: "sample"; db: string; collection: string; size: number } | 
/**  queryPlanner by default; executionStats is an explicit user action because it executes the query. */
{ cmd: "explain"; inner: ReadCommand; executionStats?: boolean };

export type ReadPrefMode = 
/**  By level: primary-preferred locally, secondary-preferred for Production-level. */
"auto" | "primary" | "primaryPreferred" | "secondary" | "secondaryPreferred" | "nearest";

export type ReadPreference = "primaryPreferred" | "secondaryPreferred" | "primary" | "secondary" | "nearest";

export type ResetReport = {
	profiles: number,
	secrets: number,
	files: number,
};

export type RoleChip = 
/**  Privileges returned and none of them writes. */
{ role: "readOnly" } | 
/**  Writes possible (privileges list a write action, or the server has no access control at all). */
{ role: "canWrite"; actions: string[]; noAuth: boolean } | 
/**  Privileges could not be read (restricted user, Atlas-like): treat as one level riskier. */
{ role: "unknown"; reason: string };

export type RunRequest = {
	/**  One cursor per tab; running again in the same tab replaces its cursor. */
	tab: string,
	connection: string,
	command: ReadCommand,
	/**  Rows per page the first window carries (default 50). */
	pageSize?: number | null,
};

export type Scheme = "standard" | "srv";

export type SecretKind = "password" | "keyPassword" | "sshSecret" | "proxyPassword";

export type SecretStoreKind = "keychain" | 
/**  Memory only: secrets last until the app quits. */
"session" | "unavailable";

export type SecretsStatus = {
	store: SecretStoreKind,
	hasPassword: boolean,
	hasKeyPassword: boolean,
	hasSshSecret: boolean,
	hasProxyPassword: boolean,
	/**  The stored secrets were typed for the connection as it is now. */
	identityMatches: boolean,
};

/**  Secrets typed at connect time (S9) for a profile that does not store them. Held in memory with the connection only. */
export type SessionSecrets = {
	password?: WireSecret | null,
	sshSecret?: WireSecret | null,
	keyPassword?: WireSecret | null,
	proxyPassword?: WireSecret | null,
};

/**  An SSH bastion. There is no jump-host field (D21): put `ProxyJump` in `~/.ssh/config`. */
export type SshSpec = {
	/**  A host name or a `~/.ssh/config` alias. */
	host: string,
	port?: number | null,
	user: string,
	auth?: TunnelAuth,
	keyFile?: string | null,
	saveSecret?: boolean,
	useSshConfig?: boolean,
	allowedHosts?: AllowedHost[],
};

export type StepId = "config" | "tunnel" | "dns" | "connect" | "tls" | "auth" | "permissions";

export type StepState = "pending" | "running" | "ok" | "warn" | "failed" | "skipped";

export type StudioStatus = {
	/**  The cargo feature is built in (always true when this answers; the UI treats a missing command as `false`). */
	compiled: boolean,
	enabled: boolean,
	/**  `full`, `loopbackOnly` (E2E jail) or `refused` (read-only jail). */
	network: string,
	connections: ConnectionView[],
	notices: Notice[],
};

export type TestReport = {
	ok: boolean,
	elapsedMs: number,
	error?: string | null,
	errorClass?: ErrorClass | null,
	connection?: ConnectionView | null,
	/**  `hello.hosts` after a success. */
	members?: string[],
	/**  Destinations the tunnel relay refused. */
	refused?: string[],
	steps?: TestStep[],
	diagnosis?: Diagnosis | null,
	hostKey?: HostKeyView | null,
	/**  Warning codes (plain-text connection to a remote host, relaxed checks, writer account). */
	warnings?: string[],
};

export type TestStep = {
	id: StepId,
	state: StepState,
	ms: number,
	note?: string | null,
};

/**  `None` = 10 s; clamped to 1..=60 s. */
export type Timeouts = {
	connectMs?: number | null,
	serverSelectionMs?: number | null,
};

export type TlsMode = "auto" | "on" | "off";

/**  Relaxed certificate checks (rustls honours only the certificate one; there is no hostname-only option). */
export type TlsRelax = "none" | "certificates";

export type TlsSpec = {
	mode?: TlsMode,
	/**  PEM file; empty means the built-in roots. */
	caFile?: string | null,
	/**  PEM file with certificate and key. */
	clientCertFile?: string | null,
	saveKeyPassword?: boolean,
};

export type TopologySpec = {
	replicaSet?: string | null,
	/**  `None` = automatic. */
	directConnection?: boolean | null,
	readPreference?: ReadPrefMode,
	maxStalenessS?: number | null,
};

/**  Serialized as `{"kind":"none"}`, `{"kind":"ssh",...}` or `{"kind":"socks5",...}`. */
export type Tunnel = { kind: "none" } | {
	kind: "ssh",
} & SshSpec | {
	kind: "socks5",
} & ProxySpec;

export type TunnelAuth = "agent" | "keyFile" | "password";

export type TunnelState = "up" | "down";

/**  The result of parsing a pasted connection string. The password stays in the Rust draft vault (`draft` is its token). */
export type UriParse = {
	spec: ConnSpec,
	hasPassword: boolean,
	hasKeyPassword: boolean,
	draft?: string | null,
	warnings: Note[],
	unsupported: Note[],
};

/**  A window of documents (canonical Extended JSON, Int64 as `{"$numberLong": "..."}`). */
export type WindowView = {
	tab: string,
	docs: string[],
	/**  Absolute position of `docs[0]` (counting the command's own `skip`). */
	offset: number,
	/**  How many documents the cursor holds right now (never above 1000). */
	loaded: number,
	/**  The 1000-document or 16 MB cap stopped the load; more exist. */
	truncated: boolean,
	hasMore: boolean,
	bytes: number,
	elapsedMs: number,
	plan?: PlanView | null,
	/**  A secondary may have served the read. */
	secondaryOk: boolean,
};

/**
 *  A secret that crosses the IPC boundary inwards only. `Debug` prints a placeholder, the value is zeroed on drop, and
 *  nothing in this crate serializes it back out.
 */
export type WireSecret = string;
