// Generated by `pnpm bindings` from crates/pathpick/src/types.rs. Do not edit.
/* eslint-disable */
// This file has been generated by Specta. Do not edit this file manually.
export type Capabilities = {
	native: boolean,
	fake: boolean,
	mode: PickerMode,
};

export type DirEntry = {
	/**  Exact on-disk name (build child paths from this). */
	name: string,
	/**  NFC form for display. */
	label: string,
	kind: EntryKind,
	hidden: boolean,
	/**  `None` when not probed (protected parents and children, beyond the 400 probe cap). */
	isRepo: boolean | null,
	protectedFolder: ProtectedFolder | null,
	package: boolean,
	size: number | null,
};

export type DirListing = {
	path: string,
	parent: string | null,
	entries: DirEntry[],
	truncated: boolean,
	totalSeen: number,
	skippedUnreadable: number,
	protectedFolder: ProtectedFolder | null,
};

export type DropEvent = {
	count: number,
};

export type EntryKind = "dir" | "file" | "symlinkDir" | "symlinkFile" | "other";

export type ListOpts = {
	hidden?: boolean,
	files?: boolean,
	extensions?: string[] | null,
};

export type NativeKind = "folder" | "folders" | "file" | "files";

/**  What the webview may ask of the native dialog. The start folder is never part of it (5.3). */
export type NativeOptions = {
	kind: NativeKind,
	/**  `workspaceRoot | workspaceRepo | scanRoot | file:<field>` */
	purpose: string,
	title?: string | null,
	extensions?: string[] | null,
	/**  A token from an earlier pick whose folder becomes the dialog's start folder. */
	startToken?: string | null,
};

export type PathKind = "repo" | "worktree" | "submodule" | "subfolder" | "bare" | "gitDir" | "notGit" | "folder" | "file";

export type PickWarning = "cloudFolder" | "network" | "externalVolume" | "insideIgnored" | "foreignOwner" | "gitfileRedirect" | "homeIsRepo" | "gitSymlink" | 
/**  Worktrees and submodules (the watcher and orphan sweep assume `.git` is a directory) until C2b ships. */
"limitedSupport";

/**
 *  A validated path plus a single-use token. `configRisks` holds key names only (never values): git config keys
 *  that can run programs, `hook:<name>` for executable hooks and `gitattributes.filter` for a filter attribute.
 */
export type Picked = {
	token: string,
	/**  Canonical display path. */
	path: string,
	/**  NFC basename. */
	name: string,
	kind: PathKind,
	/**  `"{dev}:{ino}"` of the directory. */
	identity: string,
	/**  `subfolder`: the repository root; `gitDir`: the parent of the `.git` folder. Has its own token. */
	root: Picked | null,
	/**  Linked worktree: the main repository's common git directory (`commondir`). */
	main: string | null,
	warnings: PickWarning[],
	configRisks: string[],
	remotes: PickedRemote[],
	branch: string | null,
	detached: boolean,
	protectedFolder: ProtectedFolder | null,
	viaSymlink: boolean,
	gitfileTarget: string | null,
};

/**  A remote with credentials stripped: the host only. */
export type PickedRemote = {
	name: string,
	host: string,
};

export type PickerMode = "off" | "readOnly" | "e2e";

export type Place = {
	id: string,
	label: string,
	path: string,
	exists: boolean,
};

export type ProtectedFolder = "desktop" | "documents" | "downloads" | "movies" | "music" | "pictures" | "icloud" | "cloudStorage" | "volume" | "library";

export type ScanOpts = {
	depth?: number | null,
	maxRepos?: number | null,
	includeHidden?: boolean,
};

export type ScanProgress = {
	scanId: string,
	visited: number,
	found: number,
	done: boolean,
	cancelled: boolean,
	truncated: boolean,
	reason: ScanReason | null,
	skippedProtected: string[],
	skippedSymlinks: number,
};

export type ScanReason = "depth" | "repos" | "dirs" | "time";

export type ScanResults = {
	repos: Picked[],
	next: number,
	/**  The scan's latest progress: a small scan can finish before the page has subscribed to `picker:scan`. */
	progress?: ScanProgress | null,
};

export type ScanStarted = {
	scanId: string,
};

export type StartInfo = {
	home: string,
	startPath: string,
	places: Place[],
	volumes: Volume[],
};

export type Volume = {
	name: string,
	path: string,
};
