// Generated from crates/remote/src/{api,wire}.rs. Do not edit.
/* eslint-disable */
// This file has been generated by Specta. Do not edit this file manually.
/**
 *  The actor of a tool call made inside a sub-agent. `role` is the SDK `agent_type`; `?` when the sidecar cannot name
 *  it (fail closed: the broker denies an actor it does not know).
 */
export type Actor = {
	agentId: string,
	role: string,
};

/**  The envelope: `{ agentId, seq, ts, turnId?, provider, kind, ...payload, raw? }`. */
export type AgentEvent = {
	agentId: string,
	/**  Per agent, starts at 1 (or at the `nextSeq` of a resumed session), strictly +1. */
	seq: number,
	ts: number,
	turnId?: string | null,
	provider: string,
	/**  The untouched provider message (size-capped by the host), for the Inspector's raw view. */
	raw?: unknown,
} & EventKind;

/**  One attachment of a `user.message`: what the transcript shows and the log keeps (never the contents). */
export type AttachmentRef = {
	id: string,
	name: string,
	mime: string,
	/**  Bytes (an attachment is at most 40 MB, so u32 is exact and TypeScript-safe). */
	size: number,
	/**  `image` | `text` | `pdf` | `file` */
	kind: string,
	sha256: string,
};

/**  What a provider can take as attachments of a user message (CONTRACT-CHANGE alpha attachments). */
export type AttachmentsCap = "none" | "images" | "imagesPdf" | "files";

export type AuditEntry = {
	seq: number,
	ts: number,
	event: string,
	deviceId?: string | null,
	reqId?: string | null,
	agentId?: string | null,
	risk?: string | null,
	intentHash?: string | null,
	detail?: string | null,
	prev: string,
	hash: string,
};

/**  The credential a session actually runs on, so the header can warn when it differs from the configured mode. */
export type AuthFact = {
	mode: AuthMode,
	/**  What the CLI reports (`apiKeySource`), e.g. `none` for the subscription login. */
	source: string,
	warning?: string | null,
};

export type AuthMode = "subscription" | "apiKey" | "bedrock" | "vertex" | "token";

/**  Where the shown bundle hash comes from. */
export type BundleSource = 
/**  Signed by this Mac's key and deployed by this IDE. */
"signedLocal" | 
/**  Checked against a public key the user entered or the phone pinned. */
"signedPinned" | 
/**  Seen on a custom relay, not independently verified. */
"observed" | 
/**  Legacy `expectedBundleHash` setting only. */
"settings" | "none";

/**  The build the phone will be offered: short and full hash, key fingerprint, signing sequence number and time. */
export type BundleView = {
	/**  First 16 hex digits in groups of four. */
	hashShort: string,
	hashFull: string,
	/**  First 8 bytes of sha256 of the raw public key, hex, grouped (`a1b2 c3d4 e5f6 0718`); empty when unsigned. */
	pubFingerprint: string,
	seq: number,
	builtAt: number,
	source: BundleSource,
};

/**  `yes` shows the control, `partial` shows it with a "may not apply" badge, `no` hides it. */
export type Cap = "yes" | "partial" | "no";

export type CapEntry = {
	cap: Cap,
	note?: string | null,
};

export type CapKey = "streaming" | "toolEvents" | "permissions" | "resume" | "fork" | "modelList" | "effort" | "subagents" | "usage" | "hooks" | "modelSwitch" | "cancel" | "sandbox";

/**
 *  What a device may do. There is deliberately no admin level: pairing, promotion, revocation, settings and the kill switch
 *  are desktop-only gestures. `control` found in an old file loads as `view`.
 */
export type Capability = "view" | "reply";

export type ClientMsg = 
/**  Resume: the last seq the phone holds per run (absent run = send the recent tail). */
{ t: "sync"; lastSeq: { [key in string]: number } } | { t: "answer"; opId: string; reqId: string; agentId: string; decision?: PermissionDecision | null; question?: QuestionAnswer | null; intentHash?: string | null; stepUp?: StepUpProof | null } | 
/**
 *  A follow-up to a run. `step_up` is required for a run in Automatic mode (a passkey assertion for the challenge of
 *  `prompt_step_up_key`: bound to the run and the exact text); a Bypass run is steered on the Mac.
 */
{ t: "prompt"; opId: string; agentId: string; text: string; mode: PromptMode; stepUp?: StepUpProof | null } | { t: "stop"; opId: string; agentId: string } | { t: "stopAll"; opId: string } | { t: "start"; opId: string; templateId: string; params?: unknown; stepUp?: StepUpProof | null } | { t: "diffGet"; opId: string; agentId: string; toolId: string } | { t: "stepUpBegin"; opId: string; reqId: string } | 
/**  Restarts the re-auth window: without `step_up` the Mac answers with a challenge, with it the assertion is verified. */
{ t: "reauth"; opId: string; stepUp?: StepUpProof | null } | { t: "signOut"; opId: string } | { t: "ping" };

export type CostBasis = "billed" | "estimated" | "subscription" | "included" | "unknown";

/**  Who decided a permission request. */
export type DecidedBy = "hardStop" | "roleDeny" | "saved" | "user" | 
/**  A built-in class rule, or nobody yet (an `ask`). */
"default" | 
/**  The policy channel was down, slow or garbled. */
"failClosed";

/**
 *  [`DelegateSpec`] without the prompt: what `session.info`, the run summary and the Inspector carry (the event log
 *  must not hold N prompts).
 */
export type DelegateInfo = {
	name: string,
	description: string,
	model: string,
	effort?: Effort | null,
	permission: PermissionMode,
	tools?: string[],
	disallowedTools?: string[],
	maxTurns?: number | null,
	scope: DelegateScope,
	color?: string | null,
};

/**  Where the winning copy of a delegate comes from. */
export type DelegateScope = "global" | "repo" | "builtin";

export type DeviceView = {
	id: string,
	name: string,
	capability: Capability,
	/**  `reply` device whose re-auth window ran out: effectively view-only until the passkey check. */
	reauthRequired: boolean,
	hasPasskey: boolean,
	connected: boolean,
	createdAt: number,
	lastSeenAt: number,
};

/**  What the provider actually applied (the generalized init-assert compares it with the role). */
export type Effective = {
	effort?: Effort | null,
	permission: PermissionMode,
	sandbox?: string | null,
};

/**  A mid-run change of model, effort or permission mode. */
export type EffectiveChange = {
	model?: string | null,
	effort?: Effort | null,
	permission?: PermissionMode | null,
	/**  Why `permission` changed; absent = `user`. */
	reason?: ModeChangeReason | null,
};

/**  Abstract effort ladder; resolution clamps the role's request to `ModelInfo::effort_levels`. */
export type Effort = "low" | "medium" | "high" | "xhigh" | "max";

/**  How a remote action is gated, computed by the policy (never by the client) and re-checked at answer time. */
export type Eligibility = 
/**  One tap on the phone (strict allow-list). */
"low" | 
/**  A fresh passkey assertion bound to the request. */
"stepUp" | 
/**  Never remote: the card is not offered and a remote answer is rejected and audited. */
"desktopOnly";

export type ErrorClass = "auth" | "rate" | "network" | "protocol" | "provider" | "policy" | "internal";

export type EventKind = { kind: "session.started"; nativeId?: string | null; model: string; effective: Effective; auth?: AuthFact | null; 
/**  Init-assert mismatches between the role and what the provider reports. */
assertions?: string[]; capsDelta?: Partial<{ [key in CapKey]: CapEntry }> } | 
/**  The user's prompt, emitted by the sidecar host when a turn begins so a log rebuilds the whole transcript. */
{ kind: "user.message"; messageId: string; text: string; 
/**  Files the user attached (drag-drop, paste, picker). Metadata only; the bytes stay in the attachment store. */
attachments?: AttachmentRef[] } | { kind: "text.delta"; messageId: string; text: string; 
/**  Set for text produced inside a subagent. */
parentToolId?: string | null } | { kind: "text.done"; messageId: string; text: string; parentToolId?: string | null } | 
/**  Summary text only; opaque reasoning blobs stay in `raw`. */
{ kind: "thinking.delta"; messageId: string; text: string; parentToolId?: string | null } | { kind: "tool.start"; toolId: string; name: string; toolKind: ToolKind; 
/**  Redacted input. */
input: unknown; parentToolId?: string | null } | { kind: "tool.update"; toolId: string; status: ToolStatus; output?: string | null } | { kind: "tool.result"; toolId: string; status: ToolStatus; output?: string | null; diff?: ToolDiff | null; durationMs?: number | null } | { kind: "permission.request"; reqId: string; toolId: string; intent: ToolIntent; options?: PermissionOption[]; 
/**  What the `allow_run` button would allow (display only; the host derives its own). */
sessionAllow?: SessionAllowOffer | null; 
/**  ExitPlanMode: the FULL plan text, redacted, at most 64 KiB. */
plan?: string | null; 
/**  The plan was cut at 64 KiB. */
planTruncated?: boolean | null; 
/**  ExitPlanMode: the working modes the card offers (ask, edit, automatic). */
modes?: PermissionMode[] } | { kind: "permission.resolved"; reqId: string; outcome: PermissionOutcome; by: DecidedBy } | { kind: "question.request"; reqId: string; toolId?: string | null; prompt: string; options?: QuestionOption[] } | { kind: "plan"; items: PlanItem[] } | 
/**  A note the user added to a running agent, the lead or one sub-agent. One event per state, joined by `note_id`. */
{ kind: "note"; noteId: string; state: NoteState; 
/**  The sub-agent's `Agent` tool call; absent for the lead. */
parentToolId?: string | null; 
/**  `queued` only: what the user wrote. */
text?: string | null; 
/**  `delivered` only: the tool call the note rode on. */
toolId?: string | null; 
/**  `dropped` only: `finished`, `turnEnded`, `cancelled` or `error`. */
reason?: string | null } | { kind: "usage"; usage: UsageRecord } | { kind: "status"; state: StatusState; retryAfterMs?: number | null; scope?: string | null } | { kind: "error"; class: ErrorClass; message: string; retryable: boolean } | { kind: "turn.end"; stopReason: StopReason } | { kind: "session.info"; title?: string | null; nativeId?: string | null; models?: ModelInfo[]; 
/**  The capability matrix computed for this session (runtime truth beats the static table). */
caps?: ProviderCaps | null; effective?: EffectiveChange | null; 
/**  The roles the lead may delegate to, emitted once after init (never the prompts). */
delegates?: DelegateInfo[]; 
/**  The CLI's slash commands of this session (names without the slash), from `system/init`. */
slashCommands?: string[]; 
/**  The MCP servers of this session and their state at init (`{name, status, error?, tools?}`). */
mcpServers?: McpServerInfo[] };

/**  One MCP server of a run in `session.info` (from the CLI's `system/init`): never the config, env or headers. */
export type McpServerInfo = {
	name: string,
	status: McpServerState,
	/**  The CLI's error text of a failed server (redacted by the sidecar). */
	error?: string | null,
	/**  How many tools the server offers, when known. */
	tools?: number | null,
};

/**  Connection state of an MCP server of a run, as the claude CLI reports it (`needs-auth` is `needsAuth` on the wire). */
export type McpServerState = "connected" | "failed" | "pending" | "needsAuth" | "disabled";

/**  Why a run's permission mode changed (`EffectiveChange.reason`). */
export type ModeChangeReason = "user" | "planApproved" | "resumeDowngrade" | 
/**  A repository role narrowed a resumed run. */
"roleChanged" | "provider";

export type ModelInfo = {
	id: string,
	label: string,
	/**  Empty = the model has no effort control (shown as a muted "n/a"). */
	effortLevels?: string[],
	contextTokens?: number | null,
	price?: ModelPrice | null,
	caps?: Partial<{ [key in CapKey]: CapEntry }>,
};

export type ModelPrice = {
	inputPerMTok: number | null,
	outputPerMTok: number | null,
};

/**  Cumulative tokens of one model (a run with delegates uses several; the provider reports cost per model, not per role). */
export type ModelTokens = {
	model: string,
	tokens: TokenCounts,
};

/**  Where a note the user added to a running agent stands. */
export type NoteState = 
/**  Accepted; it waits for the target's next tool call. */
"queued" | 
/**  Handed to the target together with that tool call. */
"delivered" | 
/**  The target can no longer see it (its work ended first). */
"dropped";

/**  What the Mac UI shows. */
export type OfferView = {
	/**  The QR payload: `#p=<relayHost>,<roomId>,<macStaticPub>,<otp>` (all base64url except the host). */
	qrFragment: string,
	/**  The one-time code grouped for typing: 26 base32 characters. */
	manualCode: string,
	expiresAt: number,
};

/**  Who made a call. Recorded with the resolution of a request ("answered on Mac" / "from <device>"). */
export type Origin = { kind: "desktop" } | { kind: "remote"; deviceId: string };

export type PairingView = {
	offer: OfferView | null,
	sas: SasView | null,
};

export type PendingKind = "permission" | "question";

/**
 *  What a permission card can answer. Only the options of the pending `permission.request` are accepted.
 *  `AllowOnce` and `Deny` are always possible; `AllowRun` (the card's "allow always in this session") only when the
 *  request offered it and the host can derive a session allow; `AllowAlways` (role + repo, persisted) is still never
 *  offered and is rejected with `optionNotOffered`.
 */
export type PermissionDecision = "allowOnce" | "allowRun" | "allowAlways" | "deny";

/**  The mode a run works in: `readOnly` (Plan), `ask`, `edit` (Accept edits), `automatic` or `bypass`. */
export type PermissionMode = "readOnly" | "edit" | "ask" | 
/**  Works without prompts inside the run's folders. Replaces the retired `auto`, which is still read. */
"automatic" | 
/**  No prompts, no folder boundary; every hard stop stays. Never a default, never inherited by resume. */
"bypass";

/**  What the user can answer a permission request with; `once` variants only for shell and write. */
export type PermissionOption = "allow_once" | 
/**  "Allow always in this session" (a saved allow the host keeps for the run). Offered only when `session_allow` is present. */
"allow_run" | "deny";

export type PermissionOutcome = "allow" | "deny" | "cancelled";

export type PlanItem = {
	content: string,
	/**  Provider wording (`pending`, `in_progress`, `completed`). */
	status?: string | null,
};

/**  A follow-up prompt while a turn runs: wait for the turn to end, or stop it first. */
export type PromptMode = "queue" | "interrupt";

export type ProviderCaps = {
	streaming: CapEntry,
	toolEvents: CapEntry,
	permissions: CapEntry,
	resume: CapEntry,
	fork: CapEntry,
	modelList: CapEntry,
	effort: CapEntry,
	/**
	 *  Levels the active model accepts (empty = n/a); the UI renders its effort control from this, so a
	 *  model without effort control is not special-cased anywhere.
	 */
	effortLevels?: string[],
	subagents: CapEntry,
	usage: CapEntry,
	hooks: CapEntry,
	modelSwitch: CapEntry,
	cancel: CapEntry,
	sandbox: CapEntry,
	/**  Attachments the provider accepts in a user message; absent = none. */
	attachments?: AttachmentsCap | null,
	/**  The provider takes a note for a running agent (`session/note`); absent = no. The UI shows the note input only when `true`. */
	notes?: boolean | null,
};

/**  Answer to a `question.request`: the labels of the chosen options (the option label is its identity). */
export type QuestionAnswer = {
	optionIds: string[],
	text?: string | null,
};

export type QuestionOption = {
	label: string,
	description?: string | null,
};

/**  Mac-side frame counter (against the Free plan's daily cap) and the state of the relay link. */
export type RelayStatsView = {
	/**  UTC date `YYYY-MM-DD` the counter belongs to. */
	day: string,
	framesSent: number,
	consecutiveFailures: number,
	/**  Short code of the last connect failure (`dns`, `blockedAddress`, `roomCreate:503`, ...), absent while connected. */
	lastError: string | null,
};

/**  Everything Settings > Remote shows. */
export type RemoteSettingsView = {
	state: RemoteState,
	tampered: string | null,
	relay: string,
	macName: string,
	devices: DeviceView[],
	pairing: PairingView,
	audit: AuditEntry[],
	auditLen: number,
	reauthHours: number,
	/**  The bundle hash the phone must show during pairing (from the Mac's own signed build); absent until a PWA build exists. */
	expectedBundleHash: string | null,
	/**  `blocked`: every Claude run is launched with `disableRemoteControl: true`. */
	claudeRemoteControl: string,
	e2eNote: string,
	/**  `local` | `cloudflare` | `custom`. */
	relayMode: string,
	/**  False when the relay host is not loopback and the user has not acknowledged it (or a jail forbids it). */
	relayHostAllowed: boolean,
	bundle: BundleView | null,
	relayStats: RelayStatsView,
};

export type RemoteState = 
/**  Not started: no thread, socket, timer or subscriber exists. */
"off" | 
/**  Running, relay not reachable (yet). */
"connecting" | "online" | 
/**  `devices.json` or the audit log did not verify. Remote is stopped until the user resolves it on the Mac. */
"tampered";

/**  A permission or question card, built from structured intent fields only (never model prose). */
export type ReqCard = {
	reqId: string,
	agentId: string,
	kind: PendingKind,
	toolId: string | null,
	tool: string | null,
	/**  Parsed command as the broker judged it, scrubbed and escaped; absent for non-shell tools. */
	command: string | null,
	argv: string[] | null,
	paths: string[],
	url: string | null,
	summary: string,
	question: string | null,
	options: string[],
	intentHash: string,
	risk: Risk,
	/**  What THIS device may do with it right now (capability, fatigue and re-auth window included). */
	eligibility: Eligibility,
	/**  Why `eligibility` is not `low`, in words. */
	reason: string | null,
	expiresAt: number,
	/**  ExitPlanMode: the first 2 KiB of the plan being approved (already redacted). Approving from the phone continues the run in Ask. */
	planExcerpt?: string | null,
	/**  The plan was longer than the excerpt. */
	planTruncated?: boolean | null,
};

export type Risk = "low" | "medium" | "high" | "blocked";

/**  One run row of the Home screen. */
export type RunCard = {
	agentId: string,
	title: string,
	role: string,
	provider: string,
	model: string,
	status: RunStatus,
	lastText: string,
	waitingOn: string[],
	lastSeq: number,
	startedAt: number,
	/**
	 *  The mode the run is steered under: the looser of its live effective mode and the recorded one. The phone shows it as a chip, so the
	 *  person who steers or approves sees what the step-up unlocks (permission-modes spec 5.7).
	 */
	mode?: PermissionMode | null,
};

/**  Coarse state of a run for the run list and the Rail badge. */
export type RunStatus = "running" | "needsYou" | "done" | "error";

export type SasView = {
	/**  The 6 digits to compare with the phone. */
	code: string,
	deviceName: string,
};

export type ServerMsg = { t: "hello"; capability: Capability; deviceId: string; macName: string; 
/**  The device is `view` until it re-authenticates with its passkey on the phone (window expired). */
reauthRequired: boolean } | { t: "snapshot"; runs: RunCard[]; needsYou: ReqCard[]; seqByRun: { [key in string]: number } } | { t: "event"; agentId: string; seq: number; ev: AgentEvent } | 
/**  The log rotated past the phone's seq, or the live feed lagged: start this run over from here. */
{ t: "runSnapshot"; run: RunCard; lastSeq: number; events: AgentEvent[] } | { t: "reqNew"; req: ReqCard } | { t: "reqResolved"; reqId: string; agentId: string; outcome: PermissionOutcome; by: DecidedBy; origin: Origin } | { t: "capabilityChanged"; capability: Capability; reauthRequired: boolean } | { t: "ack"; opId: string; ok: boolean; code?: string | null; message?: string | null } | { t: "stepUpChallenge"; opId: string; reqId: string; 
/**  base64url of the 32 challenge bytes the authenticator must sign (WebAuthn `challenge`). */
challenge: string; rpId: string; expiresAt: number } | { t: "diff"; opId: string; agentId: string; toolId: string; path: string; old: string | null; new: string; truncated: boolean } | { t: "pong" } | 
/**
 *  The Mac's build-signing public key (raw Ed25519, base64url) for the phone to pin; sent inside the Noise channel
 *  (never through the relay's own plain layer) when a session opens and on "send my build key to paired phones".
 */
{ t: "welcome"; bundlePub: string } | 
/**  The device was removed (or Remote was locked): the phone clears keys, queue and cache. */
{ t: "revoked" } | { t: "bye"; reason: string };

/**  What kind of saved allow an "Allow always in this session" answer would create. */
export type SessionAllowKind = "exec" | "net" | "mcp" | "write";

/**
 *  What an "Allow always in this session" answer would allow; the card states exactly this. Plain data: the UI
 *  composes the sentence from `kind` and `scope`.
 */
export type SessionAllowOffer = {
	kind: SessionAllowKind,
	/**  exec: the argv prefix joined by one space (`git status`); net: the host; mcp: `server.tool`; write: empty. */
	scope: string,
};

export type StatusState = "idle" | "thinking" | "running" | "waitingUser" | "throttled" | "retrying" | "compacting";

/**  A WebAuthn assertion, all fields base64url. Bound to the challenge the Mac issued for one request. */
export type StepUpProof = {
	credentialId: string,
	authenticatorData: string,
	clientDataJson: string,
	signature: string,
};

export type StopReason = "endTurn" | "maxTokens" | "maxTurns" | "refusal" | "cancelled" | "error";

/**  What an `Agent`/`Task` call asks for, as the broker needs it. */
export type SubagentFlags = {
	/**  The input names a `model` (it would override the role's model). */
	hasModel: boolean,
	/**  `run_in_background` as given; `None` = omitted (the CLI default is background). */
	background?: boolean | null,
	subagentType?: string | null,
};

export type TokenCounts = {
	inputTokens: number,
	outputTokens: number,
	cacheRead: number,
	cacheWrite: number,
	reasoningTokens: number,
	costUsd?: number | null,
};

export type ToolClass = "exec" | "write" | "read" | "net" | "mcp" | "other";

export type ToolDiff = {
	path: string,
	/**  Absent for a new file. */
	old?: string | null,
	new: string,
};

/**
 *  What a tool call needs the broker to judge. Serialised by hand: the three delegation fields (`actor`, `isolation`,
 *  `subagentFlags`) are left out when absent, so an intent without them is byte-identical to what it was before they
 *  existed (specta cannot express `skip_serializing_if` in its unified export, hence no derive).
 */
export type ToolIntent = {
	class: ToolClass,
	/**
	 *  The provider's own tool name (`Bash`, `Task`, `mcp__github__get_issue`); the broker needs it for
	 *  class `other` and for MCP calls.
	 */
	tool?: string | null,
	/**  The shell string, exactly as the model wrote it. This is what gets judged. */
	rawCommand?: string | null,
	/**  Already-split argv (ACP style); judged only when there is no `raw_command`. */
	argv?: string[] | null,
	paths?: string[],
	url?: string | null,
	/**  MCP server name (the part after `mcp__` of `tool`). */
	server?: string | null,
	/**  The MCP tool's `readOnlyHint` annotation, when it has one. */
	readOnlyHint?: boolean | null,
	subagentType?: string | null,
	parentToolId?: string | null,
	/**
	 *  Who made the call ((design notes: roles-orchestration-spec) 4.1): `None` = the lead of a run without a sub-agent in
	 *  flight. The harness fills it from the SDK's `agent_id`/`agent_type`, never from tool input.
	 */
	actor?: Actor | null,
	/**  `isolation` of an `Agent` input (`worktree`, `remote`), so the broker can refuse it. */
	isolation?: string | null,
	/**  Facts of an `Agent` input the broker judges (it never sees the input itself). */
	subagentFlags?: SubagentFlags | null,
	summary: string,
};

/**  The ACP tool taxonomy. */
export type ToolKind = "read" | "edit" | "delete" | "move" | "search" | "exec" | "fetch" | "think" | "mcp" | "other";

export type ToolStatus = "running" | "ok" | "error" | "denied" | "cancelled";

export type UsageRecord = {
	model: string,
	costBasis: CostBasis,
	/**  Usage of the turn that just ended. */
	perTurn: TokenCounts,
	/**  Usage of the whole run so far. */
	cumulative: TokenCounts,
	premiumRequests?: number | null,
	contextUsed?: number | null,
	contextSize?: number | null,
	/**  Cumulative per model, from the provider's per-model usage (Claude `modelUsage`). Empty = not reported. */
	perModel?: ModelTokens[],
};
