// Generated by `pnpm bindings` from crates/roles/src/types.rs. Do not edit.
/* eslint-disable */
// This file has been generated by Specta. Do not edit this file manually.
/**  Where a resumed or forked session should run when it is not an IDE run (or to override the original). */
export type AdoptOptions = {
	roleId?: string | null,
	repoIds?: string[] | null,
	/**  Fork only up to this message (`uuid` from the transcript). */
	upToMessageId?: string | null,
};

/**  Is the group passed to the Auto lead, and if not why. */
export type DelegateStatus = {
	ok: boolean,
	reason?: ExcludeReason | null,
};

export type DeleteFile = {
	id: string,
	path: string,
	scope: RoleScope,
	repoId?: string | null,
	/**  Canonical target when the file sits in a symlinked global directory. */
	symlinkTarget?: string | null,
};

/**  What the delete dialog shows before it asks for the typed name. */
export type DeletePreview = {
	name: string,
	files: DeleteFile[],
	backupDir?: string | null,
	/**  The global agents directory is a symlink: the delete needs a second typed confirmation, the target path. */
	linkTarget?: string | null,
};

export type DeleteReport = {
	deleted: DeletedFile[],
	backups: string[],
};

export type DeletedFile = {
	id: string,
	path: string,
};

/**  Why a role is not handed to the Auto lead (mirrors `intely_agent_core::delegates::ExcludeReason`). */
export type ExcludeReason = "hidden" | "otherProvider" | "noDescription" | "reservedName" | "promptTooLarge" | "repoScope" | "tooMany" | "untrusted";

/**  One row of the History view: an IDE run, a transcript started elsewhere, or both merged. */
export type HistoryEntry = {
	/**  Agent id for an IDE run, `session:<uuid>` for an external session. */
	id: string,
	sessionId?: string | null,
	source: HistorySource,
	title: string,
	role?: string | null,
	model?: string | null,
	cwd?: string | null,
	repoIds: string[],
	startedAt: number | null,
	lastModified: number | null,
	status?: RunState | null,
	tag?: string | null,
	firstPrompt?: string | null,
	gitBranch?: string | null,
};

export type HistoryQuery = {
	search?: string | null,
	tag?: string | null,
	scope?: HistoryScope | null,
	limit?: number | null,
};

export type HistoryScope = 
/**  Sessions whose working directory is one of the registered repos. */
"repos" | 
/**  Every project in the transcript store. */
"all";

export type HistorySource = 
/**  Started by this IDE (has an event log). */
"ide" | 
/**  Found in the Claude transcript store only (terminal, other IDE). */
"external";

export type ModelCaps = {
	id: string,
	label: string,
	/**  Empty: the model has no effort control. */
	effortLevels: RoleEffort[],
};

/**
 *  A role whose overlay permission differs from what its file derives (every role saved by 0.1.0 is pinned
 *  read-only). "Use automatic" removes the overlay permission.
 */
export type PermissionMismatch = {
	id: string,
	overlay: RolePermission,
	derived: RolePermission,
	/**  Reason code of the derived permission (see `Role.permission_reason`). */
	reason: string,
};

/**  The mode a run works in: `readOnly` (Plan), `ask`, `edit` (Accept edits), `automatic` or `bypass`. */
export type PermissionMode = "readOnly" | "edit" | "ask" | 
/**  Works without prompts inside the run's folders. Replaces the retired `auto`, which is still read. */
"automatic" | 
/**  No prompts, no folder boundary; every hard stop stays. Never a default, never inherited by resume. */
"bypass";

/**  Where a role's permission comes from. `ceiling`: clamped because the file lives in a repository (spec 3.2a). */
export type PermissionSource = "overlay" | "frontmatter" | "tools" | "allTools" | "default" | "overlayCorrupt" | "ceiling";

export type RewindSnapshotInfo = {
	runId: string,
	repoId: string,
	takenAt: number | null,
	files: number | null,
	/**  Files the snapshot guard left out (secrets, too large, nested repos). */
	skipped: number | null,
	/**  What a restore would do now. */
	overwrite: string[],
	recreate: string[],
	delete: string[],
	indexDiffers: boolean,
	headChanged: boolean,
};

/**  One role: the `~/.claude/agents/<name>.md` (or `<repo>/.claude/agents/<name>.md`) file plus the IDE overlay. */
export type Role = {
	/**  `name` for a global role, `name@repoId` for a repo copy. */
	id: string,
	name: string,
	description?: string | null,
	/**  Frontmatter value: an alias (`sonnet`, `haiku`, `opus`, `inherit`) or a model id. */
	model: string,
	effort?: RoleEffort | null,
	/**  False when the model or provider has no effort control: the control shows "n/a" and no effort is sent. */
	effortAvailable: boolean,
	tools?: string[],
	systemPrompt?: string | null,
	color?: string | null,
	memory?: string | null,
	scope: RoleScope,
	repoId?: string | null,
	/**  The file this role is stored in. */
	path: string,
	permission: RolePermission,
	provider: string,
	/**  Repos this role may run on; empty = every repo. */
	repoScope?: string[],
	/**  Placeholder for starting this role remotely; stored, not acted on in the alpha. */
	remoteStartable?: boolean,
	/**
	 *  Why the settings are risky or ignored: machine codes (`effortXhigh`, `effortMax`, `effortNotSent`,
	 *  `permissionModeIgnored`, `toolsUnparsable`, `mcpToolsIgnoredForDelegates`, `memoryIgnored`, `reserved`,
	 *  `duplicateName`, `caseClash`), never sentences. The UI maps them to words.
	 */
	warnings?: string[],
	permissionSource?: PermissionSource,
	/**
	 *  Machine reason: `overlay`, `permissionMode:<value>`, `tools:readOnly`, `tools:write`, `tools:all`,
	 *  `tools:none`, `tools:unparsable`, `ceiling:<repo|global|builtin>`, `overlayCorrupt`, `builtin`.
	 */
	permissionReason?: string | null,
	/**  Frontmatter `disallowedTools` (read only here). */
	disallowedTools?: string[],
	/**  Frontmatter `maxTurns` (read only here). */
	maxTurns?: number | null,
	/**  sha256 of the normalised effective fields; equal hashes mean "identical copies". */
	contentHash?: string,
	/**  True only for the synthetic role of a host built-in (no file, `path` is empty). */
	builtin?: boolean,
	/**  The effective tools include Edit/Write/NotebookEdit (or all tools) and the permission is not read-only. */
	canEdit?: boolean,
	/**  The effective tools include Bash/Monitor (or all tools) and the permission is not read-only. */
	canRun?: boolean,
	trust?: RoleTrust,
	/**
	 *  A second file of the same directory with this name: the first one is used, this one stays listed so it can
	 *  be deleted. Its id is `<id>#<file stem>`.
	 */
	shadowedByDuplicate?: boolean,
	/**  The file has a `tools` key (an absent key means "all tools"; `tools:` or `tools: []` does not). */
	toolsDeclared?: boolean,
};

/**  One file of a role group. */
export type RoleCopy = {
	/**  File id (`name` or `name@repoId`; `<id>#<stem>` for a duplicate name in one directory). */
	id: string,
	scope: RoleScope,
	repoId?: string | null,
	path: string,
	contentHash: string,
	/**  Its content hash equals the winner's. */
	sameAsWinner: boolean,
	/**  Same field names as `RoleDrift.fields`, winner vs this copy. */
	fieldsDiffer: string[],
	trust: RoleTrust,
	shadowedByDuplicate: boolean,
	warnings: string[],
};

/**
 *  What the editor sends to save a role. A field left out (`null`) stays as it is in the file and the overlay; an
 *  empty string removes a text field. A new role is global unless `scope` and `repoId` (or an `id` of the form
 *  `name@repoId`) say otherwise.
 */
export type RoleDraft = {
	id?: string | null,
	name: string,
	description?: string | null,
	model: string,
	effort?: RoleEffort | null,
	tools?: string[] | null,
	systemPrompt?: string | null,
	color?: string | null,
	memory?: string | null,
	scope?: RoleScope | null,
	repoId?: string | null,
	permission?: RolePermission | null,
	/**
	 *  Pinned into the overlay only when `permission_explicit` is true, or when it differs from what the file
	 *  derives; otherwise the role keeps deriving its permission from its file.
	 */
	permissionExplicit?: boolean | null,
	provider?: string | null,
	repoScope?: string[] | null,
	remoteStartable?: boolean | null,
	/**
	 *  Must be `true` for a save that changes a role file (`~/.claude/agents/*.md` or `<repo>/.claude/agents`):
	 *  without it the store refuses with `confirmWrite` and writes nothing. The UI sets it after the user confirmed.
	 */
	confirmWrite?: boolean | null,
};

/**  A repo copy of a role that differs from the global one. */
export type RoleDrift = {
	/**  Id of the differing copy. */
	roleId: string,
	/**  Id of the copy it differs from (the global role, or the winner of a group). */
	globalId: string,
	/**  Repository of the differing copy; empty when that copy is the global one. */
	repoId: string,
	/**
	 *  Names of the differing fields (`model`, `effort`, `tools`, `description`, `systemPrompt`, `color`, `memory`,
	 *  `disallowedTools`, `maxTurns`).
	 */
	fields: string[],
};

export type RoleEffort = "low" | "medium" | "high" | "xhigh" | "max";

/**  All copies of one role name plus the built-in of that name: the unit the Roles table shows. */
export type RoleGroup = {
	/**  The group id: the name (first copy's spelling; names compare case-insensitively). */
	name: string,
	/**  The winner with the overlay applied; a synthetic role (`builtin`, empty `path`) for a pure built-in. */
	role: Role,
	copies: RoleCopy[],
	winnerId?: string | null,
	winnerReason: WinnerReason,
	/**  Copies differ and there is no valid pin. */
	conflict: boolean,
	pin?: string | null,
	/**  The pinned copy no longer exists (or is not usable): the pin is ignored. */
	pinMissing: boolean,
	hidden: boolean,
	/**  A file overrides a built-in of the same name. */
	builtinShadowed: boolean,
	/**  Winner vs every differing copy. */
	diffs: RoleDrift[],
	delegate: DelegateStatus,
};

/**
 *  What the role may do to the working tree. Derived from the role file (`store::derive_permission`); `readOnly`
 *  is only the fail-safe default (a broken overlay, an unparsable `tools` line).
 */
export type RolePermission = "readOnly" | "edit" | "ask";

/**  What a provider offers a role; the editor's dropdowns are built from this. */
export type RoleProviderCaps = {
	provider: string,
	label: string,
	models: ModelCaps[],
	permissionModes: RolePermission[],
	tools: string[],
};

export type RoleScope = "global" | "repo";

/**
 *  Whether a role file may be handed to an agent. Global files and built-ins are trusted; a repository copy is
 *  trusted when it equals a global copy, approved when the user approved its content hash, otherwise untrusted.
 */
export type RoleTrust = "trusted" | "untrusted" | "approved";

/**  Side information of the Roles table: migration list, overlay state, skipped directories. */
export type RolesStatus = {
	/**  `roles-overlay.json` could not be parsed: every role is read-only and writes are refused until it is reset. */
	overlayCorrupt: boolean,
	/**  Where the unreadable bytes were copied. */
	overlayBackup?: string | null,
	mismatches: PermissionMismatch[],
	skippedDirs: SkippedAgentsDir[],
	/**  Canonical target of `~/.claude/agents` when it is a symlink. */
	globalDirTarget?: string | null,
	globalDir: string,
};

/**  A run as the supervisor knows it. */
export type RunRecord = {
	/**  Host agent id, or `q-<n>` while the run waits in the queue. */
	agentId: string,
	/**  Provider session id (Claude session UUID); absent until the session opened. */
	sessionId?: string | null,
	role: string,
	model: string,
	effort?: RoleEffort | null,
	cwd: string,
	repoIds: string[],
	startedAt: number | null,
	status: RunState,
	title: string,
	forkedFrom?: string | null,
	tag?: string | null,
	/**  Why a queued run waits, or why it was dropped from the queue. */
	note?: string | null,
};

export type RunState = "queued" | "running" | "needsYou" | "done" | "error";

export type RunUsage = {
	agentId: string,
	model: string,
	totals: UsageTotals,
	/**  The run continues a session that was already paid for and the share before it could only be estimated. */
	baselineEstimated: boolean,
	updatedAt: number | null,
};

export type RunsStartRequest = {
	roleId: string,
	repoIds: string[],
	prompt: string,
	/**
	 *  The run mode. The queue, tray quick actions and scripts have no dialog, so only `readOnly`, `ask`, `edit` and `automatic`
	 *  are accepted; `bypass` is refused at enqueue (`bypassNotConfirmed`) and `automatic` while the kill switch is on (`modeDisabled`).
	 */
	mode?: PermissionMode | null,
};

/**  A repository whose `.claude/agents` directory was not read (a symlink, or outside the repository). */
export type SkippedAgentsDir = {
	repoId: string,
	path: string,
	/**  `agentsDirSymlink`. */
	code: string,
	target?: string | null,
};

export type UsageSummary = {
	runs: RunUsage[],
	total: UsageTotals,
};

/**  Token counts and the cost estimate of a run or of everything. */
export type UsageTotals = {
	inputTokens: number | null,
	outputTokens: number | null,
	cacheRead: number | null,
	cacheWrite: number | null,
	reasoningTokens: number | null,
	costUsd: number | null,
};

export type WinnerReason = "onlyCopy" | "identical" | "global" | "pinned" | "primaryRepo" | "builtIn";
