// Generated by `pnpm bindings` from crates/runner/src/types.rs. Do not edit.
/* eslint-disable */
// This file has been generated by Specta. Do not edit this file manually.
export type Catalog = {
	repoId: string,
	/**  `npm`, `pnpm`, `yarn` or `bun`. */
	packageManager: string,
	scripts: ScriptInfo[],
	notes: string[],
};

/**  Masked, ANSI kept. `reset` is true after a clear: drop what you have, these lines are all there is. */
export type LogChunk = {
	serverId: string,
	startSeq: number,
	lines: string[],
	reset: boolean,
};

/**  What the jail says about starting processes right now. */
export type ProcessAccess = {
	/**  The session switch in Settings > Safety (never persisted). */
	allowed: boolean,
	/**  `off`, `readOnly` or `e2e`. */
	jail: string,
	startable: boolean,
	reason?: string | null,
};

/**
 *  `Confirm`: shown, but starting it needs a click on "Run anyway" (deploy, build, publish, docker, process managers,
 *  data migrations, remote commands). Nothing ever starts by itself.
 */
export type Safety = "normal" | "confirm";

export type ScriptGroup = "start" | "dev" | "test" | "lint" | "build" | "other";

export type ScriptInfo = {
	/**  `<source>:<name>`, e.g. `npm:dev`, `cargo:check`. */
	id: string,
	name: string,
	/**  `npm` (package.json) or `cargo`. */
	source: string,
	group: ScriptGroup,
	safety: Safety,
	/**  Why a script needs a confirmation. */
	reasons: string[],
	/**  True for every script that deploys, builds, publishes or starts a process manager: an agent must never run it. */
	forbiddenToAgents: boolean,
	/**  Node heap limit (MB) when it is 4000 or more: the "only one heavy server at a time" warning keys on it. */
	heavyMb?: number | null,
	/**  Names only, never values. */
	envNames: string[],
	/**  Port the repo's own config names for this server (e.g. Tauri `devUrl`), shown before it is detected. */
	portHint?: number | null,
	/**  What is executed, e.g. `npm run dev`. Safe to show: it holds the script name, not the body. */
	runner: string,
};

export type ServerInfo = {
	/**  `<repoId>:<script id>`; one instance per script, the log survives a restart. */
	id: string,
	repoId: string,
	script: string,
	runner: string,
	status: ServerStatus,
	pid?: number | null,
	/**  Unix seconds. */
	startedAt: number,
	exitCode?: number | null,
	/**  Listening loopback ports (from `lsof` once known, else from the output). */
	ports: number[],
	/**  `http://localhost:<port>` of the first port, loopback only. */
	url?: string | null,
	/**  Resident size of the whole process tree. */
	rssMb?: number | null,
	procs: number,
	heavyMb?: number | null,
};

export type ServerStatus = 
/**  Spawned, no port seen yet. */
"starting" | "running" | "stopping" | "exited" | 
/**  Could not be spawned. */
"failed";

export type StartRequest = {
	repoId: string,
	/**  A `ScriptInfo.id`. */
	script: string,
	/**  The user clicked "Run anyway" on a `Safety::Confirm` script. */
	confirmed?: boolean,
	/**  The user accepted the heavy-server warning. */
	allowSecondHeavy?: boolean,
};
