// Generated by `pnpm bindings` from crates/settings/src/types.rs. Do not edit.
/* eslint-disable */
// This file has been generated by Specta. Do not edit this file manually.
export type AuthModeInfo = {
	id: string,
	label: string,
	/**  The mode needs an API key or token in the Keychain (`ipc.secrets`, key `providers.<id>:default`). */
	needsKey: boolean,
};

/**  What `command -v <bin>` plus `<bin> --version` found, using the login-shell PATH. */
export type CliDetection = {
	bin: string,
	path?: string | null,
	version?: string | null,
	minVersion?: string | null,
	/**  `None` when there is no minimum or the version could not be read. */
	meetsMin?: boolean | null,
	/**  The binary exists but `--version` failed or timed out. */
	error?: string | null,
};

export type DoctorFinding = {
	/**  `None` for findings about the environment as a whole. */
	provider?: string | null,
	level: DoctorLevel,
	code: string,
	message: string,
};

export type DoctorLevel = "ok" | "info" | "warn" | "error";

/**  The command line an experimental provider runs, shown in full for the one-time confirmation. */
export type LaunchInfo = {
	/**  Absolute path of the program when found (or confirmed), else the bare name; empty for a custom ACP agent. */
	command: string,
	args: string[],
	/**  `command` is an absolute path to an executable file. */
	resolved: boolean,
	/**  The user types the command line (generic ACP agent); otherwise it is the IDE's proposal and only the program path can differ. */
	editable: boolean,
	/**
	 *  The flags were confirmed against a real agent. False for every proposal today: nothing but Claude and Codex's
	 *  app-server was ever run against the real program.
	 */
	verified: boolean,
	status: LaunchStatus,
	/**  Epoch seconds. */
	confirmedAt?: number | null,
	/**  SHA-256 over the confirmed program and arguments (first 16 hex digits shown for support). */
	hash?: string | null,
};

/**
 *  Whether the command line the IDE would start was confirmed by the user: `unconfirmed` (never), `confirmed`, or
 *  `stale` (the stored line no longer matches its hash, or the program is gone: it asks again).
 */
export type LaunchStatus = "unconfirmed" | "confirmed" | "stale";

export type ProviderHost = "sidecar" | "native";

export type ProviderInfo = {
	id: string,
	name: string,
	kind: ProviderKind,
	host: ProviderHost,
	enabled: boolean,
	state: ProviderState,
	/**  A key is stored (key modes) or the CLI is installed (login modes). */
	configured: boolean,
	authModes: AuthModeInfo[],
	authMode: string,
	/**  Not Claude: switched on only together with `Experimental providers`, confirmed command line required. */
	experimental: boolean,
	hasKey: boolean,
	/**  `None` until a detection ran (detection happens when Settings > Providers opens, never at startup). */
	cli?: CliDetection | null,
	/**  The command line for an experimental provider (absent for Claude). */
	launch?: LaunchInfo | null,
	/**  Settings > Safety: this provider may run roles that change files although its enforcement is below the write tier. */
	allowWeakWriter: boolean,
	/**  Why the state is what it is, when that is not obvious. */
	message?: string | null,
};

export type ProviderKind = "sdk" | "acp" | "cli" | "api";

/**
 *  `off -> notInstalled | needsLogin | needsKey -> probing -> ready <-> throttled | offline`, side exits `blocked`
 *  and `error` ((design notes: providers-plan) 1.3). The switch stores intent, the state says what actually runs.
 */
export type ProviderState = "off" | "notInstalled" | "needsLogin" | "needsKey" | "probing" | 
/**  An experimental provider that is installed but has no confirmed command line yet (or a changed one). */
"needsConfirm" | "ready" | "throttled" | "offline" | "blocked" | "error";

/**  Event `providers:state`. */
export type ProviderStateChange = {
	id: string,
	state: ProviderState,
};

export type ProviderTest = {
	ok: boolean,
	message?: string | null,
	latencyMs?: number | null,
};
