// Generated by `pnpm bindings` from crates/term/src/types.rs. Do not edit.
/* eslint-disable */
// This file has been generated by Specta. Do not edit this file manually.
/**  Streamed over the channel `term_open` receives; `Data` batches roughly every 16 ms. */
export type TermEvent = { kind: "data"; data: string } | { kind: "exit"; code: number | null };

export type TermOpenOptions = {
	/**  Starts in the root of this repo. */
	repoId?: string | null,
	/**  Absolute directory; wins over `repoId`. */
	cwd?: string | null,
	cols: number,
	rows: number,
};

export type TermOpened = {
	termId: string,
	cwd: string,
	shell: string,
};
