//! Generates the TypeScript types of the IPC boundary:
//! `cargo run -p intely-core --features specta --example gen_bindings -- <out.ts>` (default `ui/src/bindings.ts`).

use std::path::PathBuf;

use specta_typescript::Typescript;

fn main() {
    let out = std::env::args_os().nth(1).map(PathBuf::from).unwrap_or_else(|| {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../ui/src/bindings.ts")
    });
    Typescript::default()
        .header("// Generated by `pnpm bindings` from crates/core/src/types.rs. Do not edit.\n/* eslint-disable */")
        .export_to(&out, &intely_core::types::type_collection(), specta_serde::Format)
        .expect("export TypeScript bindings");
    println!("wrote {}", out.display());
}
