//! `cargo run -p intely-settings --features specta --example gen_bindings -- <out.ts>` (default `ui/src/bindings/settings.ts`).

use std::path::PathBuf;

use specta_typescript::Typescript;

fn main() {
    let out = std::env::args_os()
        .nth(1)
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../ui/src/bindings/settings.ts"));
    if let Some(dir) = out.parent() {
        std::fs::create_dir_all(dir).expect("create bindings directory");
    }
    Typescript::default()
        .header("// Generated by `pnpm bindings` from crates/settings/src/types.rs. Do not edit.\n/* eslint-disable */")
        .export_to(&out, &intely_settings::types::type_collection(), specta_serde::Format)
        .expect("export TypeScript bindings");
    println!("wrote {}", out.display());
}
