// Deterministic rendering of the generator outputs: data/index.json, data/texts.json, THIRD_PARTY_LICENSES.md and the
// single-component notice text. Pure functions: no clock, no environment, no absolute paths; ordering is by code unit.
import { baseId } from "./spdx.mjs";

export const SCHEMA = 1;
export const TOOL = "scripts/licenses/gen.mjs";
const SHIPPED_ORDER = ["app", "sidecar", "remote-web", "relay"];

/** Locale independent comparison (ICU collation could differ between machines). */
export const cmp = (a, b) => (a < b ? -1 : a > b ? 1 : 0);
export const byNameVersion = (a, b) => cmp(a.name, b.name) || cmp(a.version, b.version) || cmp(a.id, b.id);
export const sortShipped = (list) => [...new Set(list)].sort((a, b) => SHIPPED_ORDER.indexOf(a) - SHIPPED_ORDER.indexOf(b));

export const renderJson = (value) => `${JSON.stringify(value, null, 2)}\n`;

/** Picks the documented Component fields in the documented order and drops undefined values. */
export function toComponent(c) {
  const out = {
    id: c.id,
    kind: c.kind,
    name: c.name,
    version: c.version,
    expression: c.expression,
    chosen: c.chosen,
    copyright: c.copyright ?? [],
    textIds: c.textIds ?? [],
    shippedIn: sortShipped(c.shippedIn ?? []),
  };
  if (c.optional) out.optional = true;
  out.distributed = c.distributed !== false;
  if (c.homepage) out.homepage = c.homepage;
  if (c.sourceUrl) out.sourceUrl = c.sourceUrl;
  if (c.generic) out.generic = true;
  if (c.note) out.note = c.note;
  out.verdict = c.verdict === "attention" ? "attention" : "ok";
  return out;
}

/** Group counts by chosen license id: count desc, then id. */
export function groupsOf(components) {
  const counts = new Map();
  for (const c of components) for (const id of c.chosen) counts.set(id, (counts.get(id) ?? 0) + 1);
  return [...counts].map(([id, count]) => ({ id, count })).sort((a, b) => b.count - a.count || cmp(a.id, b.id));
}

/**
 * @param {{ project: object, components: object[], texts: Map<string, object>, generator: object }} o
 * @returns {{ index: object, textsDoc: object }}
 */
export function buildDocuments({ project, components, texts, generator }) {
  const list = components.map(toComponent).sort(byNameVersion);
  const index = { schema: SCHEMA, generator, project, groups: groupsOf(list), components: list };
  const sorted = Object.fromEntries([...texts].sort(([a], [b]) => cmp(a, b)));
  return { index, textsDoc: { schema: SCHEMA, texts: sorted } };
}

const esc = (s) => String(s).replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
const label = (c) => `${c.name} ${c.version}`;

function attentionReason(c) {
  if (c.note) return c.note;
  const why = [];
  if (c.generic) why.push("the package ships no license text, a generic template is shown");
  if (/ AND /.test(c.expression ?? "")) why.push("AND-combined license, every part applies");
  if (c.chosen.some((x) => /^(MPL|OFL|LGPL)/.test(baseId(x)))) why.push("license with file-level or notice obligations, keep unmodified and keep the notice");
  return why.join("; ") || "see the license text";
}

/** THIRD_PARTY_LICENSES.md (layout of spec 8.2). */
export function renderMarkdown({ index, textsDoc, holder, rustCount }) {
  const { project, generator, groups, components } = index;
  const L = [];
  const shipped = components.filter((c) => c.distributed);
  const notDist = components.filter((c) => !c.distributed);
  L.push("# Third-party licenses", "");
  L.push(`Generated by \`${generator.tool}\` (\`pnpm licenses:gen\`); do not edit by hand.`, "");
  L.push(`- Project: ${project.name}, ${project.license}`);
  L.push(`- Copyright holder: ${holder}`);
  L.push(`- Shipped Rust crates: ${rustCount}`);
  L.push(`- Platforms: ${generator.platforms.join(", ")}; Cargo features: ${generator.features}`);
  L.push(`- Cargo.lock sha256: ${generator.cargoLockSha256}`);
  for (const [k, v] of Object.entries(generator.pnpmLockSha256)) L.push(`- pnpm-lock.yaml sha256 (${k}): ${v}`);
  L.push("", "This file lists the third-party software that ends up in an artifact distributed with IntelyIDE: the app, the sidecar bundle, the remote-web PWA and the relay worker. Build-time and development-only packages are not listed. It is not legal advice.", "");

  L.push("## Summary", "", "| License | Components |", "|---|---|");
  for (const g of groups) L.push(`| ${esc(g.id)} | ${g.count} |`);
  L.push("");

  const attention = components.filter((c) => c.verdict === "attention");
  L.push("## Needs attention", "");
  if (attention.length === 0) L.push("Nothing.", "");
  else {
    L.push("| Component | License relied on | Why |", "|---|---|---|");
    for (const c of attention) L.push(`| ${esc(label(c))} | ${esc(c.chosen.join(", "))} | ${esc(attentionReason(c))} |`);
    L.push("");
  }

  L.push("## Not distributed", "");
  if (notDist.length === 0) L.push("Nothing.", "");
  else {
    L.push("Installed by the user on request, under the vendor's own terms. Never part of an IntelyIDE artifact.", "");
    for (const c of notDist) L.push(`- ${label(c)} (${c.expression})${c.homepage ? `, ${c.homepage}` : ""}${c.note ? `: ${c.note}` : ""}`);
    L.push("");
  }

  L.push("## Components by license", "");
  const byLicense = new Map();
  for (const c of shipped) for (const id of c.chosen) (byLicense.get(id) ?? byLicense.set(id, []).get(id)).push(c);
  for (const g of groups) {
    const members = byLicense.get(g.id);
    if (!members) continue;
    L.push(`### ${g.id}`, "");
    for (const c of members) {
      const bits = [`${label(c)}`];
      if (c.copyright.length) bits.push(c.copyright.join(" / "));
      if (c.optional) bits.push("optional feature, runtime-gated");
      if (c.sourceUrl) bits.push(`source: ${c.sourceUrl}`);
      L.push(`- ${bits.join(" - ")}`);
    }
    L.push("");
  }

  L.push("## License texts", "");
  const users = new Map();
  for (const c of components) for (const id of c.textIds) (users.get(id) ?? users.set(id, new Set()).get(id)).add(c.name);
  const projectIds = new Set(project.textIds);
  for (const [hash, t] of Object.entries(textsDoc.texts)) {
    if (!users.has(hash) && !projectIds.has(hash)) continue;
    const names = users.has(hash) ? [...users.get(hash)].sort(cmp) : [project.name];
    const shown = names.length > 12 ? `${names.slice(0, 12).join(", ")} and ${names.length - 12} more` : names.join(", ");
    L.push(`### ${t.title}${t.spdx ? ` (${t.spdx})` : ""} [${hash}]`, "", `Applies to: ${shown}`, "", "```text", t.body.replace(/\n+$/, ""), "```", "");
  }
  return `${L.join("\n").replace(/\n+$/, "")}\n`;
}

/** Plain-text notice for one shipped component (remote-web, relay), used by gen.mjs --component. */
export function renderComponentNotice({ component, banner, holder, components, texts }) {
  const L = [banner.replace(/^\/\*!\s*/, "").replace(/\s*\*\/$/, ""), "", `Copyright ${holder}`, `Licensed under GPL-3.0-or-later (any later version of the GNU GPL may be used at your option). The full text is in the LICENSE file of the source repository and at https://www.gnu.org/licenses/gpl-3.0.html.`, ""];
  if (components.length === 0) {
    L.push(`The ${component} component ships no third-party code.`, "");
    return `${L.join("\n")}`;
  }
  L.push(`Third-party software in the ${component} component:`, "");
  for (const c of components) {
    L.push(`* ${c.name} ${c.version} - ${c.expression} (relied on: ${c.chosen.join(", ")})${c.copyright.length ? ` - ${c.copyright.join(" / ")}` : ""}`);
  }
  L.push("", "License texts", "=============", "");
  const seen = new Set();
  for (const c of components) {
    for (const id of c.textIds) {
      if (seen.has(id)) continue;
      seen.add(id);
      const t = texts.get(id);
      const users = components.filter((x) => x.textIds.includes(id)).map((x) => x.name);
      L.push(`--- ${t.title}${t.spdx ? ` (${t.spdx})` : ""}, applies to: ${users.join(", ")} ---`, "", t.body.replace(/\n+$/, ""), "");
    }
  }
  return `${L.join("\n").replace(/\n+$/, "")}\n`;
}
